/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelfserviceRouteImport } from './routes/selfservice'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R2faIndexRouteImport } from './routes/2fa/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as DashDashboardRouteImport } from './routes/_dash/dashboard'
import { Route as DashAccountRouteImport } from './routes/_dash/account'
import { Route as SelfserviceOrgSlugIndexRouteImport } from './routes/selfservice/$orgSlug/index'
import { Route as DashUpdatesIndexRouteImport } from './routes/_dash/updates/index'
import { Route as DashTrialsIndexRouteImport } from './routes/_dash/trials/index'
import { Route as DashSettingsIndexRouteImport } from './routes/_dash/settings/index'
import { Route as DashProductsIndexRouteImport } from './routes/_dash/products/index'
import { Route as DashOrganizationIndexRouteImport } from './routes/_dash/organization/index'
import { Route as DashLicensesIndexRouteImport } from './routes/_dash/licenses/index'
import { Route as DashDevicesIndexRouteImport } from './routes/_dash/devices/index'
import { Route as DashAuditIndexRouteImport } from './routes/_dash/audit/index'
import { Route as SelfserviceOrgSlugAuthRouteImport } from './routes/selfservice/$orgSlug/auth'
import { Route as DashUpdatesSourcesRouteImport } from './routes/_dash/updates/sources'
import { Route as DashUpdatesReleasesRouteImport } from './routes/_dash/updates/releases'
import { Route as DashUpdatesChannelsRouteImport } from './routes/_dash/updates/channels'
import { Route as DashUpdatesChangelogsRouteImport } from './routes/_dash/updates/changelogs'
import { Route as DashUpdatesAdoptionRouteImport } from './routes/_dash/updates/adoption'
import { Route as DashProductsProductIdRouteImport } from './routes/_dash/products/$productId'
import { Route as DashLicensesLicenseIdRouteImport } from './routes/_dash/licenses/$licenseId'

const SelfserviceRoute = SelfserviceRouteImport.update({
  id: '/selfservice',
  path: '/selfservice',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R2faIndexRoute = R2faIndexRouteImport.update({
  id: '/2fa/',
  path: '/2fa/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashDashboardRoute = DashDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashRoute,
} as any)
const DashAccountRoute = DashAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashRoute,
} as any)
const SelfserviceOrgSlugIndexRoute = SelfserviceOrgSlugIndexRouteImport.update({
  id: '/$orgSlug/',
  path: '/$orgSlug/',
  getParentRoute: () => SelfserviceRoute,
} as any)
const DashUpdatesIndexRoute = DashUpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => DashRoute,
} as any)
const DashTrialsIndexRoute = DashTrialsIndexRouteImport.update({
  id: '/trials/',
  path: '/trials/',
  getParentRoute: () => DashRoute,
} as any)
const DashSettingsIndexRoute = DashSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashRoute,
} as any)
const DashProductsIndexRoute = DashProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashRoute,
} as any)
const DashOrganizationIndexRoute = DashOrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => DashRoute,
} as any)
const DashLicensesIndexRoute = DashLicensesIndexRouteImport.update({
  id: '/licenses/',
  path: '/licenses/',
  getParentRoute: () => DashRoute,
} as any)
const DashDevicesIndexRoute = DashDevicesIndexRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => DashRoute,
} as any)
const DashAuditIndexRoute = DashAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => DashRoute,
} as any)
const SelfserviceOrgSlugAuthRoute = SelfserviceOrgSlugAuthRouteImport.update({
  id: '/$orgSlug/auth',
  path: '/$orgSlug/auth',
  getParentRoute: () => SelfserviceRoute,
} as any)
const DashUpdatesSourcesRoute = DashUpdatesSourcesRouteImport.update({
  id: '/updates/sources',
  path: '/updates/sources',
  getParentRoute: () => DashRoute,
} as any)
const DashUpdatesReleasesRoute = DashUpdatesReleasesRouteImport.update({
  id: '/updates/releases',
  path: '/updates/releases',
  getParentRoute: () => DashRoute,
} as any)
const DashUpdatesChannelsRoute = DashUpdatesChannelsRouteImport.update({
  id: '/updates/channels',
  path: '/updates/channels',
  getParentRoute: () => DashRoute,
} as any)
const DashUpdatesChangelogsRoute = DashUpdatesChangelogsRouteImport.update({
  id: '/updates/changelogs',
  path: '/updates/changelogs',
  getParentRoute: () => DashRoute,
} as any)
const DashUpdatesAdoptionRoute = DashUpdatesAdoptionRouteImport.update({
  id: '/updates/adoption',
  path: '/updates/adoption',
  getParentRoute: () => DashRoute,
} as any)
const DashProductsProductIdRoute = DashProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => DashRoute,
} as any)
const DashLicensesLicenseIdRoute = DashLicensesLicenseIdRouteImport.update({
  id: '/licenses/$licenseId',
  path: '/licenses/$licenseId',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/selfservice': typeof SelfserviceRouteWithChildren
  '/account': typeof DashAccountRoute
  '/dashboard': typeof DashDashboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/2fa/': typeof R2faIndexRoute
  '/licenses/$licenseId': typeof DashLicensesLicenseIdRoute
  '/products/$productId': typeof DashProductsProductIdRoute
  '/updates/adoption': typeof DashUpdatesAdoptionRoute
  '/updates/changelogs': typeof DashUpdatesChangelogsRoute
  '/updates/channels': typeof DashUpdatesChannelsRoute
  '/updates/releases': typeof DashUpdatesReleasesRoute
  '/updates/sources': typeof DashUpdatesSourcesRoute
  '/selfservice/$orgSlug/auth': typeof SelfserviceOrgSlugAuthRoute
  '/audit/': typeof DashAuditIndexRoute
  '/devices/': typeof DashDevicesIndexRoute
  '/licenses/': typeof DashLicensesIndexRoute
  '/organization/': typeof DashOrganizationIndexRoute
  '/products/': typeof DashProductsIndexRoute
  '/settings/': typeof DashSettingsIndexRoute
  '/trials/': typeof DashTrialsIndexRoute
  '/updates/': typeof DashUpdatesIndexRoute
  '/selfservice/$orgSlug/': typeof SelfserviceOrgSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/selfservice': typeof SelfserviceRouteWithChildren
  '/account': typeof DashAccountRoute
  '/dashboard': typeof DashDashboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/2fa': typeof R2faIndexRoute
  '/licenses/$licenseId': typeof DashLicensesLicenseIdRoute
  '/products/$productId': typeof DashProductsProductIdRoute
  '/updates/adoption': typeof DashUpdatesAdoptionRoute
  '/updates/changelogs': typeof DashUpdatesChangelogsRoute
  '/updates/channels': typeof DashUpdatesChannelsRoute
  '/updates/releases': typeof DashUpdatesReleasesRoute
  '/updates/sources': typeof DashUpdatesSourcesRoute
  '/selfservice/$orgSlug/auth': typeof SelfserviceOrgSlugAuthRoute
  '/audit': typeof DashAuditIndexRoute
  '/devices': typeof DashDevicesIndexRoute
  '/licenses': typeof DashLicensesIndexRoute
  '/organization': typeof DashOrganizationIndexRoute
  '/products': typeof DashProductsIndexRoute
  '/settings': typeof DashSettingsIndexRoute
  '/trials': typeof DashTrialsIndexRoute
  '/updates': typeof DashUpdatesIndexRoute
  '/selfservice/$orgSlug': typeof SelfserviceOrgSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/login': typeof LoginRoute
  '/selfservice': typeof SelfserviceRouteWithChildren
  '/_dash/account': typeof DashAccountRoute
  '/_dash/dashboard': typeof DashDashboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/2fa/': typeof R2faIndexRoute
  '/_dash/licenses/$licenseId': typeof DashLicensesLicenseIdRoute
  '/_dash/products/$productId': typeof DashProductsProductIdRoute
  '/_dash/updates/adoption': typeof DashUpdatesAdoptionRoute
  '/_dash/updates/changelogs': typeof DashUpdatesChangelogsRoute
  '/_dash/updates/channels': typeof DashUpdatesChannelsRoute
  '/_dash/updates/releases': typeof DashUpdatesReleasesRoute
  '/_dash/updates/sources': typeof DashUpdatesSourcesRoute
  '/selfservice/$orgSlug/auth': typeof SelfserviceOrgSlugAuthRoute
  '/_dash/audit/': typeof DashAuditIndexRoute
  '/_dash/devices/': typeof DashDevicesIndexRoute
  '/_dash/licenses/': typeof DashLicensesIndexRoute
  '/_dash/organization/': typeof DashOrganizationIndexRoute
  '/_dash/products/': typeof DashProductsIndexRoute
  '/_dash/settings/': typeof DashSettingsIndexRoute
  '/_dash/trials/': typeof DashTrialsIndexRoute
  '/_dash/updates/': typeof DashUpdatesIndexRoute
  '/selfservice/$orgSlug/': typeof SelfserviceOrgSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/selfservice'
    | '/account'
    | '/dashboard'
    | '/invite/$token'
    | '/2fa/'
    | '/licenses/$licenseId'
    | '/products/$productId'
    | '/updates/adoption'
    | '/updates/changelogs'
    | '/updates/channels'
    | '/updates/releases'
    | '/updates/sources'
    | '/selfservice/$orgSlug/auth'
    | '/audit/'
    | '/devices/'
    | '/licenses/'
    | '/organization/'
    | '/products/'
    | '/settings/'
    | '/trials/'
    | '/updates/'
    | '/selfservice/$orgSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/selfservice'
    | '/account'
    | '/dashboard'
    | '/invite/$token'
    | '/2fa'
    | '/licenses/$licenseId'
    | '/products/$productId'
    | '/updates/adoption'
    | '/updates/changelogs'
    | '/updates/channels'
    | '/updates/releases'
    | '/updates/sources'
    | '/selfservice/$orgSlug/auth'
    | '/audit'
    | '/devices'
    | '/licenses'
    | '/organization'
    | '/products'
    | '/settings'
    | '/trials'
    | '/updates'
    | '/selfservice/$orgSlug'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/login'
    | '/selfservice'
    | '/_dash/account'
    | '/_dash/dashboard'
    | '/invite/$token'
    | '/2fa/'
    | '/_dash/licenses/$licenseId'
    | '/_dash/products/$productId'
    | '/_dash/updates/adoption'
    | '/_dash/updates/changelogs'
    | '/_dash/updates/channels'
    | '/_dash/updates/releases'
    | '/_dash/updates/sources'
    | '/selfservice/$orgSlug/auth'
    | '/_dash/audit/'
    | '/_dash/devices/'
    | '/_dash/licenses/'
    | '/_dash/organization/'
    | '/_dash/products/'
    | '/_dash/settings/'
    | '/_dash/trials/'
    | '/_dash/updates/'
    | '/selfservice/$orgSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  LoginRoute: typeof LoginRoute
  SelfserviceRoute: typeof SelfserviceRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  R2faIndexRoute: typeof R2faIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/selfservice': {
      id: '/selfservice'
      path: '/selfservice'
      fullPath: '/selfservice'
      preLoaderRoute: typeof SelfserviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2fa/': {
      id: '/2fa/'
      path: '/2fa'
      fullPath: '/2fa/'
      preLoaderRoute: typeof R2faIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/dashboard': {
      id: '/_dash/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashDashboardRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/account': {
      id: '/_dash/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof DashAccountRouteImport
      parentRoute: typeof DashRoute
    }
    '/selfservice/$orgSlug/': {
      id: '/selfservice/$orgSlug/'
      path: '/$orgSlug'
      fullPath: '/selfservice/$orgSlug/'
      preLoaderRoute: typeof SelfserviceOrgSlugIndexRouteImport
      parentRoute: typeof SelfserviceRoute
    }
    '/_dash/updates/': {
      id: '/_dash/updates/'
      path: '/updates'
      fullPath: '/updates/'
      preLoaderRoute: typeof DashUpdatesIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/trials/': {
      id: '/_dash/trials/'
      path: '/trials'
      fullPath: '/trials/'
      preLoaderRoute: typeof DashTrialsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/settings/': {
      id: '/_dash/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashSettingsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/products/': {
      id: '/_dash/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof DashProductsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/organization/': {
      id: '/_dash/organization/'
      path: '/organization'
      fullPath: '/organization/'
      preLoaderRoute: typeof DashOrganizationIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/licenses/': {
      id: '/_dash/licenses/'
      path: '/licenses'
      fullPath: '/licenses/'
      preLoaderRoute: typeof DashLicensesIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/devices/': {
      id: '/_dash/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof DashDevicesIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/audit/': {
      id: '/_dash/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof DashAuditIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/selfservice/$orgSlug/auth': {
      id: '/selfservice/$orgSlug/auth'
      path: '/$orgSlug/auth'
      fullPath: '/selfservice/$orgSlug/auth'
      preLoaderRoute: typeof SelfserviceOrgSlugAuthRouteImport
      parentRoute: typeof SelfserviceRoute
    }
    '/_dash/updates/sources': {
      id: '/_dash/updates/sources'
      path: '/updates/sources'
      fullPath: '/updates/sources'
      preLoaderRoute: typeof DashUpdatesSourcesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/updates/releases': {
      id: '/_dash/updates/releases'
      path: '/updates/releases'
      fullPath: '/updates/releases'
      preLoaderRoute: typeof DashUpdatesReleasesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/updates/channels': {
      id: '/_dash/updates/channels'
      path: '/updates/channels'
      fullPath: '/updates/channels'
      preLoaderRoute: typeof DashUpdatesChannelsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/updates/changelogs': {
      id: '/_dash/updates/changelogs'
      path: '/updates/changelogs'
      fullPath: '/updates/changelogs'
      preLoaderRoute: typeof DashUpdatesChangelogsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/updates/adoption': {
      id: '/_dash/updates/adoption'
      path: '/updates/adoption'
      fullPath: '/updates/adoption'
      preLoaderRoute: typeof DashUpdatesAdoptionRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/products/$productId': {
      id: '/_dash/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof DashProductsProductIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/licenses/$licenseId': {
      id: '/_dash/licenses/$licenseId'
      path: '/licenses/$licenseId'
      fullPath: '/licenses/$licenseId'
      preLoaderRoute: typeof DashLicensesLicenseIdRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashAccountRoute: typeof DashAccountRoute
  DashDashboardRoute: typeof DashDashboardRoute
  DashLicensesLicenseIdRoute: typeof DashLicensesLicenseIdRoute
  DashProductsProductIdRoute: typeof DashProductsProductIdRoute
  DashUpdatesAdoptionRoute: typeof DashUpdatesAdoptionRoute
  DashUpdatesChangelogsRoute: typeof DashUpdatesChangelogsRoute
  DashUpdatesChannelsRoute: typeof DashUpdatesChannelsRoute
  DashUpdatesReleasesRoute: typeof DashUpdatesReleasesRoute
  DashUpdatesSourcesRoute: typeof DashUpdatesSourcesRoute
  DashAuditIndexRoute: typeof DashAuditIndexRoute
  DashDevicesIndexRoute: typeof DashDevicesIndexRoute
  DashLicensesIndexRoute: typeof DashLicensesIndexRoute
  DashOrganizationIndexRoute: typeof DashOrganizationIndexRoute
  DashProductsIndexRoute: typeof DashProductsIndexRoute
  DashSettingsIndexRoute: typeof DashSettingsIndexRoute
  DashTrialsIndexRoute: typeof DashTrialsIndexRoute
  DashUpdatesIndexRoute: typeof DashUpdatesIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAccountRoute: DashAccountRoute,
  DashDashboardRoute: DashDashboardRoute,
  DashLicensesLicenseIdRoute: DashLicensesLicenseIdRoute,
  DashProductsProductIdRoute: DashProductsProductIdRoute,
  DashUpdatesAdoptionRoute: DashUpdatesAdoptionRoute,
  DashUpdatesChangelogsRoute: DashUpdatesChangelogsRoute,
  DashUpdatesChannelsRoute: DashUpdatesChannelsRoute,
  DashUpdatesReleasesRoute: DashUpdatesReleasesRoute,
  DashUpdatesSourcesRoute: DashUpdatesSourcesRoute,
  DashAuditIndexRoute: DashAuditIndexRoute,
  DashDevicesIndexRoute: DashDevicesIndexRoute,
  DashLicensesIndexRoute: DashLicensesIndexRoute,
  DashOrganizationIndexRoute: DashOrganizationIndexRoute,
  DashProductsIndexRoute: DashProductsIndexRoute,
  DashSettingsIndexRoute: DashSettingsIndexRoute,
  DashTrialsIndexRoute: DashTrialsIndexRoute,
  DashUpdatesIndexRoute: DashUpdatesIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

interface SelfserviceRouteChildren {
  SelfserviceOrgSlugAuthRoute: typeof SelfserviceOrgSlugAuthRoute
  SelfserviceOrgSlugIndexRoute: typeof SelfserviceOrgSlugIndexRoute
}

const SelfserviceRouteChildren: SelfserviceRouteChildren = {
  SelfserviceOrgSlugAuthRoute: SelfserviceOrgSlugAuthRoute,
  SelfserviceOrgSlugIndexRoute: SelfserviceOrgSlugIndexRoute,
}

const SelfserviceRouteWithChildren = SelfserviceRoute._addFileChildren(
  SelfserviceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  LoginRoute: LoginRoute,
  SelfserviceRoute: SelfserviceRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  R2faIndexRoute: R2faIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
