// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :one
UPDATE admin_recovery_codes
SET used_at = now()
WHERE admin_user_id = $1
  AND code_hash = $2
  AND used_at IS NULL
RETURNING id
`

type ConsumeRecoveryCodeParams struct {
	AdminUserID uuid.UUID `json:"admin_user_id"`
	CodeHash    string    `json:"code_hash"`
}

func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeRecoveryCode, arg.AdminUserID, arg.CodeHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admin_users (email, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, role, is_active, last_login_at, created_at, updated_at, totp_enabled, totp_secret_enc, totp_secret_nonce
`

type CreateAdminParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.Email, arg.PasswordHash, arg.Role)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpEnabled,
		&i.TotpSecretEnc,
		&i.TotpSecretNonce,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug) VALUES ($1, $2) RETURNING id, name, slug, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationMember = `-- name: CreateOrganizationMember :exec
INSERT INTO organization_members (organization_id, admin_user_id, role) VALUES ($1, $2, $3)
`

type CreateOrganizationMemberParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	AdminUserID    uuid.UUID `json:"admin_user_id"`
	Role           string    `json:"role"`
}

func (q *Queries) CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, createOrganizationMember, arg.OrganizationID, arg.AdminUserID, arg.Role)
	return err
}

const disableTOTP = `-- name: DisableTOTP :exec
UPDATE admin_users
SET totp_enabled = false,
    totp_secret_enc = NULL,
    totp_secret_nonce = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) DisableTOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableTOTP, id)
	return err
}

const enableTOTP = `-- name: EnableTOTP :exec
UPDATE admin_users
SET totp_enabled = true,
    totp_secret_enc = $1,
    totp_secret_nonce = $2,
    updated_at = now()
WHERE id = $3
`

type EnableTOTPParams struct {
	SecretEnc   []byte    `json:"secret_enc"`
	SecretNonce []byte    `json:"secret_nonce"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) EnableTOTP(ctx context.Context, arg EnableTOTPParams) error {
	_, err := q.db.Exec(ctx, enableTOTP, arg.SecretEnc, arg.SecretNonce, arg.ID)
	return err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, role, is_active, last_login_at, created_at, updated_at, totp_enabled, totp_secret_enc, totp_secret_nonce FROM admin_users WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpEnabled,
		&i.TotpSecretEnc,
		&i.TotpSecretNonce,
	)
	return i, err
}

const getAdminById = `-- name: GetAdminById :one
SELECT id, email, password_hash, role, is_active, last_login_at, created_at, updated_at, totp_enabled, totp_secret_enc, totp_secret_nonce FROM admin_users WHERE id = $1
`

func (q *Queries) GetAdminById(ctx context.Context, id uuid.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminById, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpEnabled,
		&i.TotpSecretEnc,
		&i.TotpSecretNonce,
	)
	return i, err
}

const getAdminOrganizations = `-- name: GetAdminOrganizations :many
SELECT o.id, o.name, o.slug, o.created_at, o.updated_at, om.role as member_role
FROM organizations o
JOIN organization_members om ON o.id = om.organization_id
WHERE om.admin_user_id = $1
`

type GetAdminOrganizationsRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	Slug       string             `json:"slug"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	MemberRole string             `json:"member_role"`
}

func (q *Queries) GetAdminOrganizations(ctx context.Context, adminUserID uuid.UUID) ([]GetAdminOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, getAdminOrganizations, adminUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminOrganizationsRow{}
	for rows.Next() {
		var i GetAdminOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganizationById = `-- name: GetOrganizationById :one
SELECT id, name, slug, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationById(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationById, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, created_at, updated_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationMembership = `-- name: GetOrganizationMembership :one
SELECT organization_id, admin_user_id, role, created_at
FROM organization_members
WHERE organization_id = $1 AND admin_user_id = $2
`

type GetOrganizationMembershipParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	AdminUserID    uuid.UUID `json:"admin_user_id"`
}

func (q *Queries) GetOrganizationMembership(ctx context.Context, arg GetOrganizationMembershipParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMembership, arg.OrganizationID, arg.AdminUserID)
	var i OrganizationMember
	err := row.Scan(
		&i.OrganizationID,
		&i.AdminUserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO admin_audit_log (admin_user_id, organization_id, action, resource_type, resource_id, metadata, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditLogParams struct {
	AdminUserID    pgtype.UUID `json:"admin_user_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Action         string      `json:"action"`
	ResourceType   string      `json:"resource_type"`
	ResourceID     pgtype.UUID `json:"resource_id"`
	Metadata       []byte      `json:"metadata"`
	Ip             *netip.Addr `json:"ip"`
	UserAgent      *string     `json:"user_agent"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.AdminUserID,
		arg.OrganizationID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec
INSERT INTO admin_recovery_codes (admin_user_id, code_hash)
VALUES ($1, $2)
`

type InsertRecoveryCodeParams struct {
	AdminUserID uuid.UUID `json:"admin_user_id"`
	CodeHash    string    `json:"code_hash"`
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCode, arg.AdminUserID, arg.CodeHash)
	return err
}

const invalidateRecoveryCodes = `-- name: InvalidateRecoveryCodes :exec
DELETE FROM admin_recovery_codes
WHERE admin_user_id = $1
`

func (q *Queries) InvalidateRecoveryCodes(ctx context.Context, adminUserID uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidateRecoveryCodes, adminUserID)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE admin_users
SET last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}
