// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_license.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAdminLicensesByOrganization = `-- name: CountAdminLicensesByOrganization :one
SELECT count(*)
FROM licenses lt
JOIN products p ON lt.product_id = p.id
WHERE lt.organization_id = $1::uuid
    AND ($2::text = '' OR lt.customer_email ILIKE '%' || $2::text || '%' OR p.name ILIKE '%' || $2::text || '%')
    AND (
        $3::text = 'all'
        OR ($3::text = 'active' AND lt.is_active = true AND (lt.expires_at IS NULL OR lt.expires_at > now()))
        OR ($3::text = 'inactive' AND lt.is_active = false)
        OR ($3::text = 'expired' AND lt.expires_at IS NOT NULL AND lt.expires_at <= now())
    )
    AND ($4::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR lt.product_id = $4::uuid)
    AND (
        $5::text = 'all'
        OR ($5::text = 'trial' AND lt.is_trial = true)
        OR ($5::text = 'standard' AND lt.is_trial = false)
    )
`

type CountAdminLicensesByOrganizationParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Q              string    `json:"q"`
	Status         string    `json:"status"`
	ProductID      uuid.UUID `json:"product_id"`
	Type           string    `json:"type"`
}

func (q *Queries) CountAdminLicensesByOrganization(ctx context.Context, arg CountAdminLicensesByOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminLicensesByOrganization,
		arg.OrganizationID,
		arg.Q,
		arg.Status,
		arg.ProductID,
		arg.Type,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAdminLicenseByDigest = `-- name: GetAdminLicenseByDigest :one
SELECT
    lt.id,
    lt.customer_email,
    lt.is_active,
    lt.max_activations,
    lt.created_at,
    lt.expires_at,
    lt.is_trial,
    lt.features,
    p.name AS product_name,
    p.id AS product_id,
    (SELECT count(*) FROM activations WHERE license_id = lt.id AND deactivated_at IS NULL) AS activation_count
FROM licenses lt
JOIN products p ON lt.product_id = p.id
WHERE lt.lookup_digest = $1
  AND lt.organization_id = $2::uuid
`

type GetAdminLicenseByDigestParams struct {
	LookupDigest   []byte    `json:"lookup_digest"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type GetAdminLicenseByDigestRow struct {
	ID              uuid.UUID          `json:"id"`
	CustomerEmail   string             `json:"customer_email"`
	IsActive        bool               `json:"is_active"`
	MaxActivations  int32              `json:"max_activations"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	IsTrial         bool               `json:"is_trial"`
	Features        []string           `json:"features"`
	ProductName     string             `json:"product_name"`
	ProductID       uuid.UUID          `json:"product_id"`
	ActivationCount int64              `json:"activation_count"`
}

func (q *Queries) GetAdminLicenseByDigest(ctx context.Context, arg GetAdminLicenseByDigestParams) (GetAdminLicenseByDigestRow, error) {
	row := q.db.QueryRow(ctx, getAdminLicenseByDigest, arg.LookupDigest, arg.OrganizationID)
	var i GetAdminLicenseByDigestRow
	err := row.Scan(
		&i.ID,
		&i.CustomerEmail,
		&i.IsActive,
		&i.MaxActivations,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsTrial,
		&i.Features,
		&i.ProductName,
		&i.ProductID,
		&i.ActivationCount,
	)
	return i, err
}

const getAdminLicenseDetailByOrganization = `-- name: GetAdminLicenseDetailByOrganization :one
SELECT
    lt.id,
    lt.customer_email,
    lt.is_active,
    lt.max_activations,
    lt.created_at,
    lt.expires_at,
    lt.is_trial,
    lt.features,
    p.name AS product_name,
    p.id AS product_id,
    (SELECT count(*) FROM activations WHERE license_id = lt.id AND deactivated_at IS NULL) AS activation_count
FROM licenses lt
JOIN products p ON lt.product_id = p.id
WHERE lt.id = $1 AND lt.organization_id = $2::uuid
`

type GetAdminLicenseDetailByOrganizationParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type GetAdminLicenseDetailByOrganizationRow struct {
	ID              uuid.UUID          `json:"id"`
	CustomerEmail   string             `json:"customer_email"`
	IsActive        bool               `json:"is_active"`
	MaxActivations  int32              `json:"max_activations"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	IsTrial         bool               `json:"is_trial"`
	Features        []string           `json:"features"`
	ProductName     string             `json:"product_name"`
	ProductID       uuid.UUID          `json:"product_id"`
	ActivationCount int64              `json:"activation_count"`
}

func (q *Queries) GetAdminLicenseDetailByOrganization(ctx context.Context, arg GetAdminLicenseDetailByOrganizationParams) (GetAdminLicenseDetailByOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getAdminLicenseDetailByOrganization, arg.ID, arg.OrganizationID)
	var i GetAdminLicenseDetailByOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.CustomerEmail,
		&i.IsActive,
		&i.MaxActivations,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsTrial,
		&i.Features,
		&i.ProductName,
		&i.ProductID,
		&i.ActivationCount,
	)
	return i, err
}

const getAdminLicensesByEmail = `-- name: GetAdminLicensesByEmail :many
SELECT
    lt.id,
    lt.customer_email,
    lt.is_active,
    lt.max_activations,
    lt.created_at,
    lt.expires_at,
    lt.is_trial,
    lt.features,
    p.name AS product_name,
    p.id AS product_id,
    (SELECT count(*) FROM activations WHERE license_id = lt.id AND deactivated_at IS NULL) AS activation_count
FROM licenses lt
JOIN products p ON lt.product_id = p.id
WHERE lt.organization_id = $1::uuid
  AND lower(lt.customer_email) = lower($2)
ORDER BY lt.created_at DESC
`

type GetAdminLicensesByEmailParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	CustomerEmail  string    `json:"customer_email"`
}

type GetAdminLicensesByEmailRow struct {
	ID              uuid.UUID          `json:"id"`
	CustomerEmail   string             `json:"customer_email"`
	IsActive        bool               `json:"is_active"`
	MaxActivations  int32              `json:"max_activations"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	IsTrial         bool               `json:"is_trial"`
	Features        []string           `json:"features"`
	ProductName     string             `json:"product_name"`
	ProductID       uuid.UUID          `json:"product_id"`
	ActivationCount int64              `json:"activation_count"`
}

func (q *Queries) GetAdminLicensesByEmail(ctx context.Context, arg GetAdminLicensesByEmailParams) ([]GetAdminLicensesByEmailRow, error) {
	rows, err := q.db.Query(ctx, getAdminLicensesByEmail, arg.OrganizationID, arg.CustomerEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminLicensesByEmailRow{}
	for rows.Next() {
		var i GetAdminLicensesByEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerEmail,
			&i.IsActive,
			&i.MaxActivations,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.IsTrial,
			&i.Features,
			&i.ProductName,
			&i.ProductID,
			&i.ActivationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminOverviewStatsByOrganization = `-- name: GetAdminOverviewStatsByOrganization :one
WITH license_stats AS (
    SELECT
        count(*) AS total_licenses,
        count(*) FILTER (WHERE is_active = true AND (expires_at IS NULL OR expires_at > now())) AS active_licenses,
        count(*) FILTER (WHERE expires_at IS NOT NULL AND expires_at <= now()) AS expired_licenses,
        count(*) FILTER (WHERE is_trial = true) AS total_trials,
        count(*) FILTER (WHERE is_trial = true AND is_active = true AND (expires_at IS NULL OR expires_at > now())) AS active_trials
    FROM licenses
    WHERE organization_id = $1::uuid
      AND ($2::uuid IS NULL OR product_id = $2::uuid)
), activation_stats AS (
    SELECT count(*) AS total_activations
    FROM activations a
    JOIN licenses l ON a.license_id = l.id
    WHERE l.organization_id = $1::uuid
      AND a.deactivated_at IS NULL
      AND ($2::uuid IS NULL OR l.product_id = $2::uuid)
)
SELECT
    ls.total_licenses,
    ls.active_licenses,
    ls.expired_licenses,
    (SELECT count(*) FROM products WHERE organization_id = $1::uuid) AS total_products,
    acts.total_activations,
    ls.total_trials,
    ls.active_trials
FROM license_stats ls
CROSS JOIN activation_stats acts
`

type GetAdminOverviewStatsByOrganizationParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	ProductID      pgtype.UUID `json:"product_id"`
}

type GetAdminOverviewStatsByOrganizationRow struct {
	TotalLicenses    int64 `json:"total_licenses"`
	ActiveLicenses   int64 `json:"active_licenses"`
	ExpiredLicenses  int64 `json:"expired_licenses"`
	TotalProducts    int64 `json:"total_products"`
	TotalActivations int64 `json:"total_activations"`
	TotalTrials      int64 `json:"total_trials"`
	ActiveTrials     int64 `json:"active_trials"`
}

// When product_id is provided, license/activation/trial counts are scoped to
// that product; total_products always reflects the whole organization.
func (q *Queries) GetAdminOverviewStatsByOrganization(ctx context.Context, arg GetAdminOverviewStatsByOrganizationParams) (GetAdminOverviewStatsByOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getAdminOverviewStatsByOrganization, arg.OrganizationID, arg.ProductID)
	var i GetAdminOverviewStatsByOrganizationRow
	err := row.Scan(
		&i.TotalLicenses,
		&i.ActiveLicenses,
		&i.ExpiredLicenses,
		&i.TotalProducts,
		&i.TotalActivations,
		&i.TotalTrials,
		&i.ActiveTrials,
	)
	return i, err
}

const getAdminTimeseriesByOrganization = `-- name: GetAdminTimeseriesByOrganization :many
WITH days AS (
    SELECT d::date AS day FROM generate_series(
        (now() - make_interval(days => $1::int - 1))::date,
        now()::date,
        interval '1 day'
    ) d
),
license_counts AS (
    SELECT
        l.created_at::date AS day,
        COUNT(*) FILTER (WHERE NOT l.is_trial) AS licenses,
        COUNT(*) FILTER (WHERE l.is_trial) AS trials
    FROM licenses l
    WHERE l.organization_id = $2::uuid
      AND ($3::uuid IS NULL OR l.product_id = $3::uuid)
      AND l.created_at >= (now() - make_interval(days => $1::int))
    GROUP BY l.created_at::date
),
activation_counts AS (
    SELECT
        a.created_at::date AS day,
        COUNT(*) AS activations
    FROM activations a
    JOIN licenses l ON a.license_id = l.id
    WHERE l.organization_id = $2::uuid
      AND ($3::uuid IS NULL OR l.product_id = $3::uuid)
      AND a.created_at >= (now() - make_interval(days => $1::int))
    GROUP BY a.created_at::date
)
SELECT
    d.day,
    COALESCE(lc.licenses, 0)::bigint AS licenses,
    COALESCE(lc.trials, 0)::bigint AS trials,
    COALESCE(ac.activations, 0)::bigint AS activations
FROM days d
LEFT JOIN license_counts lc ON d.day = lc.day
LEFT JOIN activation_counts ac ON d.day = ac.day
ORDER BY d.day ASC
`

type GetAdminTimeseriesByOrganizationParams struct {
	Days           int32       `json:"days"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	ProductID      pgtype.UUID `json:"product_id"`
}

type GetAdminTimeseriesByOrganizationRow struct {
	Day         pgtype.Date `json:"day"`
	Licenses    int64       `json:"licenses"`
	Trials      int64       `json:"trials"`
	Activations int64       `json:"activations"`
}

func (q *Queries) GetAdminTimeseriesByOrganization(ctx context.Context, arg GetAdminTimeseriesByOrganizationParams) ([]GetAdminTimeseriesByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, getAdminTimeseriesByOrganization, arg.Days, arg.OrganizationID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminTimeseriesByOrganizationRow{}
	for rows.Next() {
		var i GetAdminTimeseriesByOrganizationRow
		if err := rows.Scan(
			&i.Day,
			&i.Licenses,
			&i.Trials,
			&i.Activations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminLicenseActivationsByOrganization = `-- name: ListAdminLicenseActivationsByOrganization :many
SELECT
    a.id,
    a.license_id,
    a.created_at,
    a.checked_in_at,
    d.id AS device_id,
    d.hwid_hash,
    d.hostname,
    d.created_at AS device_created_at
FROM activations a
JOIN devices d ON a.device_id = d.id
JOIN licenses l ON a.license_id = l.id
WHERE a.license_id = $1 AND l.organization_id = $2::uuid AND a.deactivated_at IS NULL
ORDER BY a.created_at DESC
`

type ListAdminLicenseActivationsByOrganizationParams struct {
	LicenseID      uuid.UUID `json:"license_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type ListAdminLicenseActivationsByOrganizationRow struct {
	ID              uuid.UUID          `json:"id"`
	LicenseID       uuid.UUID          `json:"license_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CheckedInAt     pgtype.Timestamptz `json:"checked_in_at"`
	DeviceID        uuid.UUID          `json:"device_id"`
	HwidHash        []byte             `json:"hwid_hash"`
	Hostname        *string            `json:"hostname"`
	DeviceCreatedAt pgtype.Timestamptz `json:"device_created_at"`
}

func (q *Queries) ListAdminLicenseActivationsByOrganization(ctx context.Context, arg ListAdminLicenseActivationsByOrganizationParams) ([]ListAdminLicenseActivationsByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listAdminLicenseActivationsByOrganization, arg.LicenseID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminLicenseActivationsByOrganizationRow{}
	for rows.Next() {
		var i ListAdminLicenseActivationsByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.LicenseID,
			&i.CreatedAt,
			&i.CheckedInAt,
			&i.DeviceID,
			&i.HwidHash,
			&i.Hostname,
			&i.DeviceCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminLicensesByOrganization = `-- name: ListAdminLicensesByOrganization :many
SELECT
    lt.id,
    lt.customer_email,
    lt.is_active,
    lt.max_activations,
    lt.created_at,
    lt.expires_at,
    lt.is_trial,
    p.name AS product_name,
    (SELECT count(*) FROM activations WHERE license_id = lt.id AND deactivated_at IS NULL) AS activation_count
FROM licenses lt
JOIN products p ON lt.product_id = p.id
WHERE lt.organization_id = $1::uuid
    AND ($2::text = '' OR lt.customer_email ILIKE '%' || $2::text || '%' OR p.name ILIKE '%' || $2::text || '%')
    AND (
        $3::text = 'all'
        OR ($3::text = 'active' AND lt.is_active = true AND (lt.expires_at IS NULL OR lt.expires_at > now()))
        OR ($3::text = 'inactive' AND lt.is_active = false)
        OR ($3::text = 'expired' AND lt.expires_at IS NOT NULL AND lt.expires_at <= now())
    )
    AND ($4::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR lt.product_id = $4::uuid)
    AND (
        $5::text = 'all'
        OR ($5::text = 'trial' AND lt.is_trial = true)
        OR ($5::text = 'standard' AND lt.is_trial = false)
    )
ORDER BY lt.created_at DESC
LIMIT $7
OFFSET $6
`

type ListAdminLicensesByOrganizationParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Q              string    `json:"q"`
	Status         string    `json:"status"`
	ProductID      uuid.UUID `json:"product_id"`
	Type           string    `json:"type"`
	Offset         int32     `json:"offset"`
	Limit          int32     `json:"limit"`
}

type ListAdminLicensesByOrganizationRow struct {
	ID              uuid.UUID          `json:"id"`
	CustomerEmail   string             `json:"customer_email"`
	IsActive        bool               `json:"is_active"`
	MaxActivations  int32              `json:"max_activations"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	IsTrial         bool               `json:"is_trial"`
	ProductName     string             `json:"product_name"`
	ActivationCount int64              `json:"activation_count"`
}

func (q *Queries) ListAdminLicensesByOrganization(ctx context.Context, arg ListAdminLicensesByOrganizationParams) ([]ListAdminLicensesByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listAdminLicensesByOrganization,
		arg.OrganizationID,
		arg.Q,
		arg.Status,
		arg.ProductID,
		arg.Type,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminLicensesByOrganizationRow{}
	for rows.Next() {
		var i ListAdminLicensesByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerEmail,
			&i.IsActive,
			&i.MaxActivations,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.IsTrial,
			&i.ProductName,
			&i.ActivationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminRecentLicensesByOrganization = `-- name: ListAdminRecentLicensesByOrganization :many
SELECT
    lt.id,
    lt.customer_email,
    lt.is_active,
    lt.max_activations,
    lt.created_at,
    lt.expires_at,
    lt.is_trial,
    lt.features,
    p.name AS product_name,
    (SELECT count(*) FROM activations WHERE license_id = lt.id AND deactivated_at IS NULL) AS activation_count
FROM licenses lt
JOIN products p ON lt.product_id = p.id
WHERE lt.organization_id = $1::uuid
ORDER BY lt.created_at DESC
LIMIT $2
`

type ListAdminRecentLicensesByOrganizationParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Limit          int32     `json:"limit"`
}

type ListAdminRecentLicensesByOrganizationRow struct {
	ID              uuid.UUID          `json:"id"`
	CustomerEmail   string             `json:"customer_email"`
	IsActive        bool               `json:"is_active"`
	MaxActivations  int32              `json:"max_activations"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	IsTrial         bool               `json:"is_trial"`
	Features        []string           `json:"features"`
	ProductName     string             `json:"product_name"`
	ActivationCount int64              `json:"activation_count"`
}

func (q *Queries) ListAdminRecentLicensesByOrganization(ctx context.Context, arg ListAdminRecentLicensesByOrganizationParams) ([]ListAdminRecentLicensesByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listAdminRecentLicensesByOrganization, arg.OrganizationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminRecentLicensesByOrganizationRow{}
	for rows.Next() {
		var i ListAdminRecentLicensesByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerEmail,
			&i.IsActive,
			&i.MaxActivations,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.IsTrial,
			&i.Features,
			&i.ProductName,
			&i.ActivationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminTrialsByOrganization = `-- name: ListAdminTrialsByOrganization :many
SELECT
    lt.id,
    lt.customer_email,
    lt.is_active,
    lt.max_activations,
    lt.created_at,
    lt.expires_at,
    lt.is_trial,
    p.name AS product_name,
    (SELECT count(*) FROM activations WHERE license_id = lt.id AND deactivated_at IS NULL) AS activation_count
FROM licenses lt
JOIN products p ON lt.product_id = p.id
WHERE lt.organization_id = $1::uuid
    AND lt.is_trial = true
    AND ($2::uuid IS NULL OR lt.product_id = $2::uuid)
    AND ($3::text = '' OR lt.customer_email ILIKE '%' || $3::text || '%' OR p.name ILIKE '%' || $3::text || '%')
    AND (
        $4::text = 'all'
        OR ($4::text = 'active' AND lt.is_active = true AND (lt.expires_at IS NULL OR lt.expires_at > now()))
        OR ($4::text = 'expired' AND lt.expires_at IS NOT NULL AND lt.expires_at <= now())
    )
ORDER BY lt.created_at DESC
LIMIT 500
`

type ListAdminTrialsByOrganizationParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	ProductID      pgtype.UUID `json:"product_id"`
	Q              string      `json:"q"`
	Status         string      `json:"status"`
}

type ListAdminTrialsByOrganizationRow struct {
	ID              uuid.UUID          `json:"id"`
	CustomerEmail   string             `json:"customer_email"`
	IsActive        bool               `json:"is_active"`
	MaxActivations  int32              `json:"max_activations"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	IsTrial         bool               `json:"is_trial"`
	ProductName     string             `json:"product_name"`
	ActivationCount int64              `json:"activation_count"`
}

func (q *Queries) ListAdminTrialsByOrganization(ctx context.Context, arg ListAdminTrialsByOrganizationParams) ([]ListAdminTrialsByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listAdminTrialsByOrganization,
		arg.OrganizationID,
		arg.ProductID,
		arg.Q,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminTrialsByOrganizationRow{}
	for rows.Next() {
		var i ListAdminTrialsByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerEmail,
			&i.IsActive,
			&i.MaxActivations,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.IsTrial,
			&i.ProductName,
			&i.ActivationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAdminLicense = `-- name: RevokeAdminLicense :one
UPDATE licenses SET is_active = false
WHERE id = $1::uuid
  AND organization_id = $2::uuid
  AND is_active = true
RETURNING id
`

type RevokeAdminLicenseParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) RevokeAdminLicense(ctx context.Context, arg RevokeAdminLicenseParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeAdminLicense, arg.ID, arg.OrganizationID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const revokeAdminLicenseByDigest = `-- name: RevokeAdminLicenseByDigest :one
UPDATE licenses SET is_active = false
WHERE lookup_digest = $1
  AND organization_id = $2::uuid
  AND is_active = true
RETURNING id
`

type RevokeAdminLicenseByDigestParams struct {
	LookupDigest   []byte    `json:"lookup_digest"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) RevokeAdminLicenseByDigest(ctx context.Context, arg RevokeAdminLicenseByDigestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeAdminLicenseByDigest, arg.LookupDigest, arg.OrganizationID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
