// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admin_users (email, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, role, is_active, last_login_at, created_at, updated_at
`

type CreateAdminParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.Email, arg.PasswordHash, arg.Role)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug) VALUES ($1, $2) RETURNING id, name, slug, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationMember = `-- name: CreateOrganizationMember :exec
INSERT INTO organization_members (organization_id, admin_user_id, role) VALUES ($1, $2, $3)
`

type CreateOrganizationMemberParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	AdminUserID    uuid.UUID `json:"admin_user_id"`
	Role           string    `json:"role"`
}

func (q *Queries) CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, createOrganizationMember, arg.OrganizationID, arg.AdminUserID, arg.Role)
	return err
}

const deleteExpiredAdminEmailCodes = `-- name: DeleteExpiredAdminEmailCodes :exec
DELETE FROM admin_email_codes
WHERE expires_at < now() - INTERVAL '1 day'
`

func (q *Queries) DeleteExpiredAdminEmailCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAdminEmailCodes)
	return err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, role, is_active, last_login_at, created_at, updated_at FROM admin_users WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminById = `-- name: GetAdminById :one
SELECT id, email, password_hash, role, is_active, last_login_at, created_at, updated_at FROM admin_users WHERE id = $1
`

func (q *Queries) GetAdminById(ctx context.Context, id uuid.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminById, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminOrganizations = `-- name: GetAdminOrganizations :many
SELECT o.id, o.name, o.slug, o.created_at, o.updated_at, om.role as member_role
FROM organizations o
JOIN organization_members om ON o.id = om.organization_id
WHERE om.admin_user_id = $1
`

type GetAdminOrganizationsRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	Slug       string             `json:"slug"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	MemberRole string             `json:"member_role"`
}

func (q *Queries) GetAdminOrganizations(ctx context.Context, adminUserID uuid.UUID) ([]GetAdminOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, getAdminOrganizations, adminUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminOrganizationsRow{}
	for rows.Next() {
		var i GetAdminOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestAdminEmailCode = `-- name: GetLatestAdminEmailCode :one
SELECT id, admin_user_id, code_hash, attempts, expires_at, used_at, created_at FROM admin_email_codes
WHERE admin_user_id = $1
  AND used_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAdminEmailCode(ctx context.Context, adminUserID uuid.UUID) (AdminEmailCode, error) {
	row := q.db.QueryRow(ctx, getLatestAdminEmailCode, adminUserID)
	var i AdminEmailCode
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationById = `-- name: GetOrganizationById :one
SELECT id, name, slug, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationById(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationById, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, created_at, updated_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationMembership = `-- name: GetOrganizationMembership :one
SELECT organization_id, admin_user_id, role, created_at
FROM organization_members
WHERE organization_id = $1 AND admin_user_id = $2
`

type GetOrganizationMembershipParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	AdminUserID    uuid.UUID `json:"admin_user_id"`
}

func (q *Queries) GetOrganizationMembership(ctx context.Context, arg GetOrganizationMembershipParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMembership, arg.OrganizationID, arg.AdminUserID)
	var i OrganizationMember
	err := row.Scan(
		&i.OrganizationID,
		&i.AdminUserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const incrementAdminEmailCodeAttempts = `-- name: IncrementAdminEmailCodeAttempts :one
UPDATE admin_email_codes
SET attempts = attempts + 1
WHERE id = $1
RETURNING attempts
`

func (q *Queries) IncrementAdminEmailCodeAttempts(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementAdminEmailCodeAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const insertAdminEmailCode = `-- name: InsertAdminEmailCode :exec
INSERT INTO admin_email_codes (admin_user_id, code_hash, expires_at)
VALUES ($1, $2, $3)
`

type InsertAdminEmailCodeParams struct {
	AdminUserID uuid.UUID          `json:"admin_user_id"`
	CodeHash    string             `json:"code_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertAdminEmailCode(ctx context.Context, arg InsertAdminEmailCodeParams) error {
	_, err := q.db.Exec(ctx, insertAdminEmailCode, arg.AdminUserID, arg.CodeHash, arg.ExpiresAt)
	return err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO admin_audit_log (admin_user_id, organization_id, action, resource_type, resource_id, metadata, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditLogParams struct {
	AdminUserID    pgtype.UUID `json:"admin_user_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Action         string      `json:"action"`
	ResourceType   string      `json:"resource_type"`
	ResourceID     pgtype.UUID `json:"resource_id"`
	Metadata       []byte      `json:"metadata"`
	Ip             *netip.Addr `json:"ip"`
	UserAgent      *string     `json:"user_agent"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.AdminUserID,
		arg.OrganizationID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const invalidateAdminEmailCodes = `-- name: InvalidateAdminEmailCodes :exec
UPDATE admin_email_codes
SET used_at = now()
WHERE admin_user_id = $1
  AND used_at IS NULL
`

func (q *Queries) InvalidateAdminEmailCodes(ctx context.Context, adminUserID uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidateAdminEmailCodes, adminUserID)
	return err
}

const markAdminEmailCodeUsed = `-- name: MarkAdminEmailCodeUsed :exec
UPDATE admin_email_codes
SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkAdminEmailCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAdminEmailCodeUsed, id)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE admin_users
SET last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}
