// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogsByOrganization = `-- name: CountAuditLogsByOrganization :one
SELECT count(*) FROM admin_audit_log
WHERE organization_id = $1::uuid
`

func (q *Queries) CountAuditLogsByOrganization(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsByOrganization, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAuditLogsByOrganization = `-- name: ListAuditLogsByOrganization :many
SELECT
    a.id,
    a.action,
    a.resource_type,
    a.resource_id,
    a.metadata,
    a.ip,
    a.user_agent,
    a.created_at,
    au.email AS admin_email
FROM admin_audit_log a
LEFT JOIN admin_users au ON a.admin_user_id = au.id
WHERE a.organization_id = $1::uuid
ORDER BY a.created_at DESC
LIMIT $3 OFFSET $2
`

type ListAuditLogsByOrganizationParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Offset         int32     `json:"offset"`
	Limit          int32     `json:"limit"`
}

type ListAuditLogsByOrganizationRow struct {
	ID           uuid.UUID          `json:"id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	Metadata     []byte             `json:"metadata"`
	Ip           *netip.Addr        `json:"ip"`
	UserAgent    *string            `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	AdminEmail   *string            `json:"admin_email"`
}

func (q *Queries) ListAuditLogsByOrganization(ctx context.Context, arg ListAuditLogsByOrganizationParams) ([]ListAuditLogsByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByOrganization, arg.OrganizationID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsByOrganizationRow{}
	for rows.Next() {
		var i ListAuditLogsByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
			&i.AdminEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
