// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: changelogs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countReleasesForChangelog = `-- name: CountReleasesForChangelog :one
SELECT count(*) FROM update_releases WHERE changelog_id = $1
`

func (q *Queries) CountReleasesForChangelog(ctx context.Context, changelogID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReleasesForChangelog, changelogID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChangelog = `-- name: CreateChangelog :one
INSERT INTO changelogs (organization_id, product_id, title, body)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, product_id, title, body, created_at, updated_at
`

type CreateChangelogParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProductID      uuid.UUID `json:"product_id"`
	Title          string    `json:"title"`
	Body           string    `json:"body"`
}

func (q *Queries) CreateChangelog(ctx context.Context, arg CreateChangelogParams) (Changelog, error) {
	row := q.db.QueryRow(ctx, createChangelog,
		arg.OrganizationID,
		arg.ProductID,
		arg.Title,
		arg.Body,
	)
	var i Changelog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChangelog = `-- name: DeleteChangelog :one
DELETE FROM changelogs
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, product_id, title, body, created_at, updated_at
`

type DeleteChangelogParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteChangelog(ctx context.Context, arg DeleteChangelogParams) (Changelog, error) {
	row := q.db.QueryRow(ctx, deleteChangelog, arg.ID, arg.OrganizationID)
	var i Changelog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChangelog = `-- name: GetChangelog :one
SELECT id, organization_id, product_id, title, body, created_at, updated_at FROM changelogs WHERE id = $1
`

func (q *Queries) GetChangelog(ctx context.Context, id uuid.UUID) (Changelog, error) {
	row := q.db.QueryRow(ctx, getChangelog, id)
	var i Changelog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChangelogsForProduct = `-- name: ListChangelogsForProduct :many
SELECT id, organization_id, product_id, title, body, created_at, updated_at FROM changelogs
WHERE product_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListChangelogsForProduct(ctx context.Context, productID uuid.UUID) ([]Changelog, error) {
	rows, err := q.db.Query(ctx, listChangelogsForProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Changelog{}
	for rows.Next() {
		var i Changelog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProductID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReleaseChangelog = `-- name: SetReleaseChangelog :one
UPDATE update_releases
SET changelog_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, organization_id, product_id, channel_id, platform, version, build_number, status, release_notes, published_at, created_at, updated_at, changelog, changelog_id
`

type SetReleaseChangelogParams struct {
	ID          uuid.UUID   `json:"id"`
	ChangelogID pgtype.UUID `json:"changelog_id"`
}

func (q *Queries) SetReleaseChangelog(ctx context.Context, arg SetReleaseChangelogParams) (UpdateRelease, error) {
	row := q.db.QueryRow(ctx, setReleaseChangelog, arg.ID, arg.ChangelogID)
	var i UpdateRelease
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.ChannelID,
		&i.Platform,
		&i.Version,
		&i.BuildNumber,
		&i.Status,
		&i.ReleaseNotes,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Changelog,
		&i.ChangelogID,
	)
	return i, err
}

const updateChangelog = `-- name: UpdateChangelog :one
UPDATE changelogs
SET title = $3, body = $4, updated_at = now()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, product_id, title, body, created_at, updated_at
`

type UpdateChangelogParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Title          string    `json:"title"`
	Body           string    `json:"body"`
}

func (q *Queries) UpdateChangelog(ctx context.Context, arg UpdateChangelogParams) (Changelog, error) {
	row := q.db.QueryRow(ctx, updateChangelog,
		arg.ID,
		arg.OrganizationID,
		arg.Title,
		arg.Body,
	)
	var i Changelog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
