// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package db

import (
	"context"
)

const createDevice = `-- name: CreateDevice :one
insert into devices(license_id, hwid_hash, hostname) values($1, $2, $3) returning id, license_id, hwid_hash, hostname, created_at
`

type CreateDeviceParams struct {
	LicenseID int32   `json:"license_id"`
	HwidHash  []byte  `json:"hwid_hash"`
	Hostname  *string `json:"hostname"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.LicenseID, arg.HwidHash, arg.Hostname)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.LicenseID,
		&i.HwidHash,
		&i.Hostname,
		&i.CreatedAt,
	)
	return i, err
}
