// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDevice = `-- name: CreateDevice :one
insert into devices(license_id, hwid_hash, hostname) values($1, $2, $3) returning id, hwid_hash, hostname, created_at, license_id
`

type CreateDeviceParams struct {
	LicenseID uuid.UUID `json:"license_id"`
	HwidHash  []byte    `json:"hwid_hash"`
	Hostname  *string   `json:"hostname"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.LicenseID, arg.HwidHash, arg.Hostname)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.HwidHash,
		&i.Hostname,
		&i.CreatedAt,
		&i.LicenseID,
	)
	return i, err
}

const getDeviceByLicenseAndHwidHash = `-- name: GetDeviceByLicenseAndHwidHash :one
select id, hwid_hash, hostname, created_at, license_id from devices where license_id = $1 and hwid_hash = $2
`

type GetDeviceByLicenseAndHwidHashParams struct {
	LicenseID uuid.UUID `json:"license_id"`
	HwidHash  []byte    `json:"hwid_hash"`
}

func (q *Queries) GetDeviceByLicenseAndHwidHash(ctx context.Context, arg GetDeviceByLicenseAndHwidHashParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByLicenseAndHwidHash, arg.LicenseID, arg.HwidHash)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.HwidHash,
		&i.Hostname,
		&i.CreatedAt,
		&i.LicenseID,
	)
	return i, err
}
