// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diagnostics.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredClientCheckins = `-- name: DeleteExpiredClientCheckins :execrows
DELETE FROM client_checkins
WHERE created_at < now() - make_interval(days => $1::int)
`

func (q *Queries) DeleteExpiredClientCheckins(ctx context.Context, retentionDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredClientCheckins, retentionDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertClientCheckin = `-- name: InsertClientCheckin :one
INSERT INTO client_checkins (
    organization_id, product_id, license_id, activation_id,
    version, build, platform, arch, os_version
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, organization_id, product_id, license_id, activation_id, version, build, platform, arch, os_version, created_at
`

type InsertClientCheckinParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProductID      uuid.UUID `json:"product_id"`
	LicenseID      uuid.UUID `json:"license_id"`
	ActivationID   uuid.UUID `json:"activation_id"`
	Version        string    `json:"version"`
	Build          *string   `json:"build"`
	Platform       *string   `json:"platform"`
	Arch           *string   `json:"arch"`
	OsVersion      *string   `json:"os_version"`
}

func (q *Queries) InsertClientCheckin(ctx context.Context, arg InsertClientCheckinParams) (ClientCheckin, error) {
	row := q.db.QueryRow(ctx, insertClientCheckin,
		arg.OrganizationID,
		arg.ProductID,
		arg.LicenseID,
		arg.ActivationID,
		arg.Version,
		arg.Build,
		arg.Platform,
		arg.Arch,
		arg.OsVersion,
	)
	var i ClientCheckin
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.LicenseID,
		&i.ActivationID,
		&i.Version,
		&i.Build,
		&i.Platform,
		&i.Arch,
		&i.OsVersion,
		&i.CreatedAt,
	)
	return i, err
}

const listDailyLatestClientVersions = `-- name: ListDailyLatestClientVersions :many
SELECT date, version, count(*)::bigint AS device_count
FROM (
    SELECT DISTINCT ON (c.created_at::date, c.activation_id)
        c.created_at::date AS date,
        c.activation_id,
        c.version
    FROM client_checkins c
    JOIN activations a ON a.id = c.activation_id
    WHERE c.organization_id = $1::uuid
      AND c.created_at >= now() - make_interval(days => $2::int)
      AND (
          $3::uuid IS NULL
          OR c.product_id = $3::uuid
      )
      AND a.deactivated_at IS NULL
    ORDER BY c.created_at::date, c.activation_id, c.created_at DESC, c.id DESC
) latest
GROUP BY date, version
ORDER BY date, version
`

type ListDailyLatestClientVersionsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Days           int32       `json:"days"`
	ProductID      pgtype.UUID `json:"product_id"`
}

type ListDailyLatestClientVersionsRow struct {
	Date        pgtype.Date `json:"date"`
	Version     string      `json:"version"`
	DeviceCount int64       `json:"device_count"`
}

func (q *Queries) ListDailyLatestClientVersions(ctx context.Context, arg ListDailyLatestClientVersionsParams) ([]ListDailyLatestClientVersionsRow, error) {
	rows, err := q.db.Query(ctx, listDailyLatestClientVersions, arg.OrganizationID, arg.Days, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDailyLatestClientVersionsRow{}
	for rows.Next() {
		var i ListDailyLatestClientVersionsRow
		if err := rows.Scan(&i.Date, &i.Version, &i.DeviceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestClientCheckins = `-- name: ListLatestClientCheckins :many
WITH ranked AS (
    SELECT
        c.id, c.organization_id, c.product_id, c.license_id, c.activation_id, c.version, c.build, c.platform, c.arch, c.os_version, c.created_at,
        row_number() OVER (
            PARTITION BY c.activation_id
            ORDER BY c.created_at DESC, c.id DESC
        ) AS position
    FROM client_checkins c
    WHERE c.organization_id = $1::uuid
      AND c.created_at >= now() - make_interval(days => $2::int)
      AND (
          $3::uuid IS NULL
          OR c.product_id = $3::uuid
      )
)
SELECT
    ranked.activation_id,
    d.hostname,
    ranked.version,
    ranked.build,
    ranked.platform,
    ranked.arch,
    ranked.os_version,
    ranked.created_at
FROM ranked
JOIN activations a ON a.id = ranked.activation_id
JOIN devices d ON d.id = a.device_id
WHERE ranked.position = 1
  AND a.deactivated_at IS NULL
ORDER BY ranked.created_at DESC
`

type ListLatestClientCheckinsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Days           int32       `json:"days"`
	ProductID      pgtype.UUID `json:"product_id"`
}

type ListLatestClientCheckinsRow struct {
	ActivationID uuid.UUID          `json:"activation_id"`
	Hostname     *string            `json:"hostname"`
	Version      string             `json:"version"`
	Build        *string            `json:"build"`
	Platform     *string            `json:"platform"`
	Arch         *string            `json:"arch"`
	OsVersion    *string            `json:"os_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListLatestClientCheckins(ctx context.Context, arg ListLatestClientCheckinsParams) ([]ListLatestClientCheckinsRow, error) {
	rows, err := q.db.Query(ctx, listLatestClientCheckins, arg.OrganizationID, arg.Days, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestClientCheckinsRow{}
	for rows.Next() {
		var i ListLatestClientCheckinsRow
		if err := rows.Scan(
			&i.ActivationID,
			&i.Hostname,
			&i.Version,
			&i.Build,
			&i.Platform,
			&i.Arch,
			&i.OsVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
