// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: features.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addChannelRequiredFeature = `-- name: AddChannelRequiredFeature :exec
INSERT INTO update_channel_required_features (channel_id, feature_id)
VALUES ($1, $2)
ON CONFLICT (channel_id, feature_id) DO NOTHING
`

type AddChannelRequiredFeatureParams struct {
	ChannelID uuid.UUID `json:"channel_id"`
	FeatureID uuid.UUID `json:"feature_id"`
}

func (q *Queries) AddChannelRequiredFeature(ctx context.Context, arg AddChannelRequiredFeatureParams) error {
	_, err := q.db.Exec(ctx, addChannelRequiredFeature, arg.ChannelID, arg.FeatureID)
	return err
}

const addLicenseFeature = `-- name: AddLicenseFeature :exec
INSERT INTO license_features (license_id, feature_id, source, source_window_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (license_id, feature_id) DO NOTHING
`

type AddLicenseFeatureParams struct {
	LicenseID      uuid.UUID   `json:"license_id"`
	FeatureID      uuid.UUID   `json:"feature_id"`
	Source         string      `json:"source"`
	SourceWindowID pgtype.UUID `json:"source_window_id"`
}

func (q *Queries) AddLicenseFeature(ctx context.Context, arg AddLicenseFeatureParams) error {
	_, err := q.db.Exec(ctx, addLicenseFeature,
		arg.LicenseID,
		arg.FeatureID,
		arg.Source,
		arg.SourceWindowID,
	)
	return err
}

const addLicenseFeatureByKey = `-- name: AddLicenseFeatureByKey :exec
INSERT INTO license_features (license_id, feature_id, source)
SELECT $1, pf.id, $3
FROM product_features pf
WHERE pf.organization_id = $2 AND pf.product_id = $4 AND pf.key = $5
ON CONFLICT (license_id, feature_id) DO NOTHING
`

type AddLicenseFeatureByKeyParams struct {
	LicenseID      uuid.UUID `json:"license_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Source         string    `json:"source"`
	ProductID      uuid.UUID `json:"product_id"`
	Key            string    `json:"key"`
}

func (q *Queries) AddLicenseFeatureByKey(ctx context.Context, arg AddLicenseFeatureByKeyParams) error {
	_, err := q.db.Exec(ctx, addLicenseFeatureByKey,
		arg.LicenseID,
		arg.OrganizationID,
		arg.Source,
		arg.ProductID,
		arg.Key,
	)
	return err
}

const archiveProductFeature = `-- name: ArchiveProductFeature :one
UPDATE product_features
SET archived_at = now()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, organization_id, product_id, key, name, description, archived_at, created_at
`

func (q *Queries) ArchiveProductFeature(ctx context.Context, id uuid.UUID) (ProductFeature, error) {
	row := q.db.QueryRow(ctx, archiveProductFeature, id)
	var i ProductFeature
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const copyLicenseFeatures = `-- name: CopyLicenseFeatures :exec
INSERT INTO license_features (license_id, feature_id, source, source_window_id)
SELECT $1::uuid, feature_id, source, source_window_id
FROM license_features
WHERE license_id = $2::uuid
ON CONFLICT (license_id, feature_id) DO NOTHING
`

type CopyLicenseFeaturesParams struct {
	NewLicenseID uuid.UUID `json:"new_license_id"`
	OldLicenseID uuid.UUID `json:"old_license_id"`
}

func (q *Queries) CopyLicenseFeatures(ctx context.Context, arg CopyLicenseFeaturesParams) error {
	_, err := q.db.Exec(ctx, copyLicenseFeatures, arg.NewLicenseID, arg.OldLicenseID)
	return err
}

const createFeatureWindow = `-- name: CreateFeatureWindow :one
INSERT INTO product_feature_windows (organization_id, product_id, feature_id, starts_at, ends_at, applies_to, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, product_id, feature_id, starts_at, ends_at, applies_to, is_active, created_at
`

type CreateFeatureWindowParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	FeatureID      uuid.UUID          `json:"feature_id"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	AppliesTo      string             `json:"applies_to"`
	IsActive       bool               `json:"is_active"`
}

func (q *Queries) CreateFeatureWindow(ctx context.Context, arg CreateFeatureWindowParams) (ProductFeatureWindow, error) {
	row := q.db.QueryRow(ctx, createFeatureWindow,
		arg.OrganizationID,
		arg.ProductID,
		arg.FeatureID,
		arg.StartsAt,
		arg.EndsAt,
		arg.AppliesTo,
		arg.IsActive,
	)
	var i ProductFeatureWindow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.FeatureID,
		&i.StartsAt,
		&i.EndsAt,
		&i.AppliesTo,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createProductFeature = `-- name: CreateProductFeature :one
INSERT INTO product_features (organization_id, product_id, key, name, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, product_id, key, name, description, archived_at, created_at
`

type CreateProductFeatureParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProductID      uuid.UUID `json:"product_id"`
	Key            string    `json:"key"`
	Name           *string   `json:"name"`
	Description    *string   `json:"description"`
}

func (q *Queries) CreateProductFeature(ctx context.Context, arg CreateProductFeatureParams) (ProductFeature, error) {
	row := q.db.QueryRow(ctx, createProductFeature,
		arg.OrganizationID,
		arg.ProductID,
		arg.Key,
		arg.Name,
		arg.Description,
	)
	var i ProductFeature
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFeatureWindow = `-- name: DeleteFeatureWindow :one
DELETE FROM product_feature_windows
WHERE id = $1 AND organization_id = $2
RETURNING id
`

type DeleteFeatureWindowParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteFeatureWindow(ctx context.Context, arg DeleteFeatureWindowParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteFeatureWindow, arg.ID, arg.OrganizationID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteProductFeature = `-- name: DeleteProductFeature :one
DELETE FROM product_features
WHERE id = $1 AND organization_id = $2
RETURNING id
`

type DeleteProductFeatureParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteProductFeature(ctx context.Context, arg DeleteProductFeatureParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteProductFeature, arg.ID, arg.OrganizationID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getActiveFeatureWindowsForProduct = `-- name: GetActiveFeatureWindowsForProduct :many
SELECT pfw.id, pfw.organization_id, pfw.product_id, pfw.feature_id, pfw.starts_at, pfw.ends_at, pfw.applies_to, pfw.is_active, pfw.created_at, pf.key AS feature_key
FROM product_feature_windows pfw
JOIN product_features pf ON pf.id = pfw.feature_id
WHERE pfw.product_id = $1
  AND pfw.is_active = true
  AND pfw.starts_at <= $2
  AND pfw.ends_at > $2
  AND (pfw.applies_to = 'all' OR pfw.applies_to = $3)
ORDER BY pf.key
`

type GetActiveFeatureWindowsForProductParams struct {
	ProductID uuid.UUID          `json:"product_id"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	AppliesTo string             `json:"applies_to"`
}

type GetActiveFeatureWindowsForProductRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	FeatureID      uuid.UUID          `json:"feature_id"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	AppliesTo      string             `json:"applies_to"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	FeatureKey     string             `json:"feature_key"`
}

func (q *Queries) GetActiveFeatureWindowsForProduct(ctx context.Context, arg GetActiveFeatureWindowsForProductParams) ([]GetActiveFeatureWindowsForProductRow, error) {
	rows, err := q.db.Query(ctx, getActiveFeatureWindowsForProduct, arg.ProductID, arg.StartsAt, arg.AppliesTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveFeatureWindowsForProductRow{}
	for rows.Next() {
		var i GetActiveFeatureWindowsForProductRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProductID,
			&i.FeatureID,
			&i.StartsAt,
			&i.EndsAt,
			&i.AppliesTo,
			&i.IsActive,
			&i.CreatedAt,
			&i.FeatureKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelRequiredFeatureKeys = `-- name: GetChannelRequiredFeatureKeys :many

SELECT pf.key
FROM update_channel_required_features crf
JOIN product_features pf ON pf.id = crf.feature_id
WHERE crf.channel_id = $1
ORDER BY pf.key
`

// ============ update_channel_required_features ============
func (q *Queries) GetChannelRequiredFeatureKeys(ctx context.Context, channelID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getChannelRequiredFeatureKeys, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeatureWindowsByOrganization = `-- name: GetFeatureWindowsByOrganization :many
SELECT pfw.id, pfw.organization_id, pfw.product_id, pfw.feature_id, pfw.starts_at, pfw.ends_at, pfw.applies_to, pfw.is_active, pfw.created_at, pf.key AS feature_key, p.name AS product_name
FROM product_feature_windows pfw
JOIN product_features pf ON pf.id = pfw.feature_id
JOIN products p ON p.id = pfw.product_id
WHERE pfw.organization_id = $1
ORDER BY pfw.starts_at DESC
`

type GetFeatureWindowsByOrganizationRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	FeatureID      uuid.UUID          `json:"feature_id"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	AppliesTo      string             `json:"applies_to"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	FeatureKey     string             `json:"feature_key"`
	ProductName    string             `json:"product_name"`
}

func (q *Queries) GetFeatureWindowsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]GetFeatureWindowsByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, getFeatureWindowsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFeatureWindowsByOrganizationRow{}
	for rows.Next() {
		var i GetFeatureWindowsByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProductID,
			&i.FeatureID,
			&i.StartsAt,
			&i.EndsAt,
			&i.AppliesTo,
			&i.IsActive,
			&i.CreatedAt,
			&i.FeatureKey,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeatureWindowsByProduct = `-- name: GetFeatureWindowsByProduct :many

SELECT pfw.id, pfw.organization_id, pfw.product_id, pfw.feature_id, pfw.starts_at, pfw.ends_at, pfw.applies_to, pfw.is_active, pfw.created_at, pf.key AS feature_key
FROM product_feature_windows pfw
JOIN product_features pf ON pf.id = pfw.feature_id
WHERE pfw.product_id = $1
ORDER BY pfw.starts_at DESC
`

type GetFeatureWindowsByProductRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	FeatureID      uuid.UUID          `json:"feature_id"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	AppliesTo      string             `json:"applies_to"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	FeatureKey     string             `json:"feature_key"`
}

// ============ product_feature_windows ============
func (q *Queries) GetFeatureWindowsByProduct(ctx context.Context, productID uuid.UUID) ([]GetFeatureWindowsByProductRow, error) {
	rows, err := q.db.Query(ctx, getFeatureWindowsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFeatureWindowsByProductRow{}
	for rows.Next() {
		var i GetFeatureWindowsByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProductID,
			&i.FeatureID,
			&i.StartsAt,
			&i.EndsAt,
			&i.AppliesTo,
			&i.IsActive,
			&i.CreatedAt,
			&i.FeatureKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLicenseFeatureKeys = `-- name: GetLicenseFeatureKeys :many

SELECT pf.key
FROM license_features lf
JOIN product_features pf ON pf.id = lf.feature_id
WHERE lf.license_id = $1
ORDER BY pf.key
`

// ============ license_features ============
func (q *Queries) GetLicenseFeatureKeys(ctx context.Context, licenseID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getLicenseFeatureKeys, licenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductFeatureByID = `-- name: GetProductFeatureByID :one
SELECT id, organization_id, product_id, key, name, description, archived_at, created_at FROM product_features WHERE id = $1
`

func (q *Queries) GetProductFeatureByID(ctx context.Context, id uuid.UUID) (ProductFeature, error) {
	row := q.db.QueryRow(ctx, getProductFeatureByID, id)
	var i ProductFeature
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProductFeatureByKey = `-- name: GetProductFeatureByKey :one
SELECT id, organization_id, product_id, key, name, description, archived_at, created_at FROM product_features
WHERE organization_id = $1 AND product_id = $2 AND key = $3
`

type GetProductFeatureByKeyParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProductID      uuid.UUID `json:"product_id"`
	Key            string    `json:"key"`
}

func (q *Queries) GetProductFeatureByKey(ctx context.Context, arg GetProductFeatureByKeyParams) (ProductFeature, error) {
	row := q.db.QueryRow(ctx, getProductFeatureByKey, arg.OrganizationID, arg.ProductID, arg.Key)
	var i ProductFeature
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProductFeaturesByOrganization = `-- name: GetProductFeaturesByOrganization :many
SELECT id, organization_id, product_id, key, name, description, archived_at, created_at FROM product_features
WHERE organization_id = $1
ORDER BY product_id, key
`

func (q *Queries) GetProductFeaturesByOrganization(ctx context.Context, organizationID uuid.UUID) ([]ProductFeature, error) {
	rows, err := q.db.Query(ctx, getProductFeaturesByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductFeature{}
	for rows.Next() {
		var i ProductFeature
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProductID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductFeaturesByProduct = `-- name: GetProductFeaturesByProduct :many

SELECT id, organization_id, product_id, key, name, description, archived_at, created_at FROM product_features
WHERE product_id = $1
ORDER BY key
`

// ============ product_features catalog ============
func (q *Queries) GetProductFeaturesByProduct(ctx context.Context, productID uuid.UUID) ([]ProductFeature, error) {
	rows, err := q.db.Query(ctx, getProductFeaturesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductFeature{}
	for rows.Next() {
		var i ProductFeature
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProductID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChannelRequiredFeatures = `-- name: SetChannelRequiredFeatures :exec
DELETE FROM update_channel_required_features WHERE channel_id = $1
`

func (q *Queries) SetChannelRequiredFeatures(ctx context.Context, channelID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setChannelRequiredFeatures, channelID)
	return err
}

const setLicenseFeatures = `-- name: SetLicenseFeatures :exec
DELETE FROM license_features WHERE license_id = $1
`

func (q *Queries) SetLicenseFeatures(ctx context.Context, licenseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setLicenseFeatures, licenseID)
	return err
}

const updateFeatureWindow = `-- name: UpdateFeatureWindow :one
UPDATE product_feature_windows
SET feature_id = $2,
    starts_at = $3,
    ends_at = $4,
    applies_to = $5,
    is_active = $6
WHERE id = $1 AND organization_id = $7
RETURNING id, organization_id, product_id, feature_id, starts_at, ends_at, applies_to, is_active, created_at
`

type UpdateFeatureWindowParams struct {
	ID             uuid.UUID          `json:"id"`
	FeatureID      uuid.UUID          `json:"feature_id"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	AppliesTo      string             `json:"applies_to"`
	IsActive       bool               `json:"is_active"`
	OrganizationID uuid.UUID          `json:"organization_id"`
}

func (q *Queries) UpdateFeatureWindow(ctx context.Context, arg UpdateFeatureWindowParams) (ProductFeatureWindow, error) {
	row := q.db.QueryRow(ctx, updateFeatureWindow,
		arg.ID,
		arg.FeatureID,
		arg.StartsAt,
		arg.EndsAt,
		arg.AppliesTo,
		arg.IsActive,
		arg.OrganizationID,
	)
	var i ProductFeatureWindow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.FeatureID,
		&i.StartsAt,
		&i.EndsAt,
		&i.AppliesTo,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateProductFeature = `-- name: UpdateProductFeature :one
UPDATE product_features
SET name = $2, description = $3
WHERE id = $1
RETURNING id, organization_id, product_id, key, name, description, archived_at, created_at
`

type UpdateProductFeatureParams struct {
	ID          uuid.UUID `json:"id"`
	Name        *string   `json:"name"`
	Description *string   `json:"description"`
}

func (q *Queries) UpdateProductFeature(ctx context.Context, arg UpdateProductFeatureParams) (ProductFeature, error) {
	row := q.db.QueryRow(ctx, updateProductFeature, arg.ID, arg.Name, arg.Description)
	var i ProductFeature
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}
