// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: licenses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLicense = `-- name: CreateLicense :one
INSERT INTO licenses(product_id, max_activations, lookup_digest, key_phc, customer_email) values($1, $2, $3, $4, $5) returning id, product_id, lookup_digest, key_phc, customer_email, max_activations, is_active, expires_at, created_at
`

type CreateLicenseParams struct {
	ProductID      *int32 `json:"product_id"`
	MaxActivations int32  `json:"max_activations"`
	LookupDigest   []byte `json:"lookup_digest"`
	KeyPhc         string `json:"key_phc"`
	CustomerEmail  string `json:"customer_email"`
}

func (q *Queries) CreateLicense(ctx context.Context, arg CreateLicenseParams) (License, error) {
	row := q.db.QueryRow(ctx, createLicense,
		arg.ProductID,
		arg.MaxActivations,
		arg.LookupDigest,
		arg.KeyPhc,
		arg.CustomerEmail,
	)
	var i License
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.LookupDigest,
		&i.KeyPhc,
		&i.CustomerEmail,
		&i.MaxActivations,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLicenseByDigest = `-- name: GetLicenseByDigest :one
select id, product_id, lookup_digest, key_phc, customer_email, max_activations, is_active, expires_at, created_at from licenses where lookup_digest = $1
`

func (q *Queries) GetLicenseByDigest(ctx context.Context, lookupDigest []byte) (License, error) {
	row := q.db.QueryRow(ctx, getLicenseByDigest, lookupDigest)
	var i License
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.LookupDigest,
		&i.KeyPhc,
		&i.CustomerEmail,
		&i.MaxActivations,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLicenseById = `-- name: GetLicenseById :one
select id, product_id, lookup_digest, key_phc, customer_email, max_activations, is_active, expires_at, created_at from licenses where id = $1
`

func (q *Queries) GetLicenseById(ctx context.Context, id int32) (License, error) {
	row := q.db.QueryRow(ctx, getLicenseById, id)
	var i License
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.LookupDigest,
		&i.KeyPhc,
		&i.CustomerEmail,
		&i.MaxActivations,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listByCustomerEmail = `-- name: ListByCustomerEmail :many
select lt.is_active, lt.id, lt.max_activations, lt.expires_at, p.name from licenses lt join products p on lt.product_id = p.id where customer_email = $1
`

type ListByCustomerEmailRow struct {
	IsActive       bool               `json:"is_active"`
	ID             int32              `json:"id"`
	MaxActivations int32              `json:"max_activations"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	Name           string             `json:"name"`
}

func (q *Queries) ListByCustomerEmail(ctx context.Context, customerEmail string) ([]ListByCustomerEmailRow, error) {
	rows, err := q.db.Query(ctx, listByCustomerEmail, customerEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListByCustomerEmailRow{}
	for rows.Next() {
		var i ListByCustomerEmailRow
		if err := rows.Scan(
			&i.IsActive,
			&i.ID,
			&i.MaxActivations,
			&i.ExpiresAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
