// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: licenses.sql

package db

import (
	"context"
)

const getLicenseById = `-- name: GetLicenseById :one
select id, product_id, key_hash, max_activations, is_active, expires_at, created_at from licenses where id = $1
`

func (q *Queries) GetLicenseById(ctx context.Context, id int32) (License, error) {
	row := q.db.QueryRow(ctx, getLicenseById, id)
	var i License
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.KeyHash,
		&i.MaxActivations,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
