// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMCPTokenByOrganization = `-- name: GetMCPTokenByOrganization :one
SELECT organization_id, token_id, token_hash, token_prefix, created_by, regenerated_at, last_used_at FROM mcp_tokens WHERE organization_id = $1
`

func (q *Queries) GetMCPTokenByOrganization(ctx context.Context, organizationID uuid.UUID) (McpToken, error) {
	row := q.db.QueryRow(ctx, getMCPTokenByOrganization, organizationID)
	var i McpToken
	err := row.Scan(
		&i.OrganizationID,
		&i.TokenID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.CreatedBy,
		&i.RegeneratedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getMCPTokenByTokenID = `-- name: GetMCPTokenByTokenID :one
SELECT organization_id, token_id, token_hash, token_prefix, created_by, regenerated_at, last_used_at FROM mcp_tokens WHERE token_id = $1
`

func (q *Queries) GetMCPTokenByTokenID(ctx context.Context, tokenID string) (McpToken, error) {
	row := q.db.QueryRow(ctx, getMCPTokenByTokenID, tokenID)
	var i McpToken
	err := row.Scan(
		&i.OrganizationID,
		&i.TokenID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.CreatedBy,
		&i.RegeneratedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const touchMCPTokenLastUsed = `-- name: TouchMCPTokenLastUsed :exec
UPDATE mcp_tokens SET last_used_at = now() WHERE organization_id = $1
`

func (q *Queries) TouchMCPTokenLastUsed(ctx context.Context, organizationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchMCPTokenLastUsed, organizationID)
	return err
}

const upsertMCPToken = `-- name: UpsertMCPToken :one
INSERT INTO mcp_tokens (organization_id, token_id, token_hash, token_prefix, created_by, regenerated_at, last_used_at)
VALUES ($1, $2, $3, $4, $5, now(), NULL)
ON CONFLICT (organization_id) DO UPDATE
SET token_id = EXCLUDED.token_id,
    token_hash = EXCLUDED.token_hash,
    token_prefix = EXCLUDED.token_prefix,
    created_by = EXCLUDED.created_by,
    regenerated_at = now(),
    last_used_at = NULL
RETURNING organization_id, token_id, token_hash, token_prefix, created_by, regenerated_at, last_used_at
`

type UpsertMCPTokenParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	TokenID        string      `json:"token_id"`
	TokenHash      []byte      `json:"token_hash"`
	TokenPrefix    string      `json:"token_prefix"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) UpsertMCPToken(ctx context.Context, arg UpsertMCPTokenParams) (McpToken, error) {
	row := q.db.QueryRow(ctx, upsertMCPToken,
		arg.OrganizationID,
		arg.TokenID,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.CreatedBy,
	)
	var i McpToken
	err := row.Scan(
		&i.OrganizationID,
		&i.TokenID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.CreatedBy,
		&i.RegeneratedAt,
		&i.LastUsedAt,
	)
	return i, err
}
