// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Activation struct {
	ID          int32              `json:"id"`
	DeviceID    uuid.UUID          `json:"device_id"`
	LicenseID   int32              `json:"license_id"`
	CheckedInAt pgtype.Timestamptz `json:"checked_in_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Device struct {
	ID        uuid.UUID          `json:"id"`
	LicenseID int32              `json:"license_id"`
	HwidHash  []byte             `json:"hwid_hash"`
	Hostname  *string            `json:"hostname"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type License struct {
	ID             int32              `json:"id"`
	ProductID      *int32             `json:"product_id"`
	LookupDigest   []byte             `json:"lookup_digest"`
	KeyPhc         string             `json:"key_phc"`
	CustomerEmail  string             `json:"customer_email"`
	MaxActivations int32              `json:"max_activations"`
	IsActive       bool               `json:"is_active"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Features       []string           `json:"features"`
}

type Product struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Version   *string            `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SelfServiceToken struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	TokenHash string             `json:"token_hash"`
	Purpose   string             `json:"purpose"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedIp *netip.Addr        `json:"created_ip"`
	UserAgent *string            `json:"user_agent"`
}
