// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activation struct {
	ID          int32              `json:"id"`
	LicenseID   pgtype.Int4        `json:"license_id"`
	Hwid        string             `json:"hwid"`
	LastCheckIn pgtype.Timestamptz `json:"last_check_in"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type License struct {
	ID             int32              `json:"id"`
	ProductID      pgtype.Int4        `json:"product_id"`
	KeyHash        string             `json:"key_hash"`
	MaxActivations pgtype.Int4        `json:"max_activations"`
	IsActive       pgtype.Bool        `json:"is_active"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Version   pgtype.Text        `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
