// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Activation struct {
	DeviceID           uuid.UUID          `json:"device_id"`
	CheckedInAt        pgtype.Timestamptz `json:"checked_in_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ID                 uuid.UUID          `json:"id"`
	LicenseID          uuid.UUID          `json:"license_id"`
	DeactivatedAt      pgtype.Timestamptz `json:"deactivated_at"`
	DeactivationReason *string            `json:"deactivation_reason"`
}

type AdminAuditLog struct {
	ID             uuid.UUID          `json:"id"`
	AdminUserID    pgtype.UUID        `json:"admin_user_id"`
	Action         string             `json:"action"`
	ResourceType   string             `json:"resource_type"`
	ResourceID     pgtype.UUID        `json:"resource_id"`
	Metadata       []byte             `json:"metadata"`
	Ip             *netip.Addr        `json:"ip"`
	UserAgent      *string            `json:"user_agent"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
}

type AdminRecoveryCode struct {
	ID          uuid.UUID          `json:"id"`
	AdminUserID uuid.UUID          `json:"admin_user_id"`
	CodeHash    string             `json:"code_hash"`
	UsedAt      pgtype.Timestamptz `json:"used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AdminUser struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	IsActive        bool               `json:"is_active"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	TotpEnabled     bool               `json:"totp_enabled"`
	TotpSecretEnc   []byte             `json:"totp_secret_enc"`
	TotpSecretNonce []byte             `json:"totp_secret_nonce"`
}

type Changelog struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ClientCheckin struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	LicenseID      uuid.UUID          `json:"license_id"`
	ActivationID   uuid.UUID          `json:"activation_id"`
	Version        string             `json:"version"`
	Build          *string            `json:"build"`
	Platform       *string            `json:"platform"`
	Arch           *string            `json:"arch"`
	OsVersion      *string            `json:"os_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Device struct {
	ID        uuid.UUID          `json:"id"`
	HwidHash  []byte             `json:"hwid_hash"`
	Hostname  *string            `json:"hostname"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	LicenseID uuid.UUID          `json:"license_id"`
}

type License struct {
	LookupDigest   []byte             `json:"lookup_digest"`
	KeyPhc         string             `json:"key_phc"`
	CustomerEmail  string             `json:"customer_email"`
	MaxActivations int32              `json:"max_activations"`
	IsActive       bool               `json:"is_active"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Features       []string           `json:"features"`
	ID             uuid.UUID          `json:"id"`
	ProductID      pgtype.UUID        `json:"product_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	IsTrial        bool               `json:"is_trial"`
	TrialHwidHash  []byte             `json:"trial_hwid_hash"`
}

type LicenseFeature struct {
	LicenseID      uuid.UUID          `json:"license_id"`
	FeatureID      uuid.UUID          `json:"feature_id"`
	GrantedAt      pgtype.Timestamptz `json:"granted_at"`
	Source         string             `json:"source"`
	SourceWindowID pgtype.UUID        `json:"source_window_id"`
}

type McpToken struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	TokenID        string             `json:"token_id"`
	TokenHash      []byte             `json:"token_hash"`
	TokenPrefix    string             `json:"token_prefix"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	RegeneratedAt  pgtype.Timestamptz `json:"regenerated_at"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
}

type Organization struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationInvite struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Email          string             `json:"email"`
	Role           string             `json:"role"`
	TokenHash      string             `json:"token_hash"`
	InvitedBy      pgtype.UUID        `json:"invited_by"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type OrganizationMember struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	AdminUserID    uuid.UUID          `json:"admin_user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	Name           string             `json:"name"`
	Version        *string            `json:"version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	LogoUrl        *string            `json:"logo_url"`
}

type ProductFeature struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	Key            string             `json:"key"`
	Name           *string            `json:"name"`
	Description    *string            `json:"description"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ProductFeatureWindow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	FeatureID      uuid.UUID          `json:"feature_id"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	AppliesTo      string             `json:"applies_to"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ProductStorageConfig struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	Backend        string             `json:"backend"`
	Config         []byte             `json:"config"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ProductUpdateConfig struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	Platform       string             `json:"platform"`
	ChannelID      uuid.UUID          `json:"channel_id"`
	ProviderKey    string             `json:"provider_key"`
	Config         []byte             `json:"config"`
	Enabled        bool               `json:"enabled"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type SelfServiceToken struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	TokenHash string             `json:"token_hash"`
	Purpose   string             `json:"purpose"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedIp *netip.Addr        `json:"created_ip"`
	UserAgent *string            `json:"user_agent"`
}

type Session struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

type UpdateArtifact struct {
	ID                   uuid.UUID          `json:"id"`
	ReleaseID            uuid.UUID          `json:"release_id"`
	ArtifactType         string             `json:"artifact_type"`
	Os                   string             `json:"os"`
	Arch                 string             `json:"arch"`
	Url                  string             `json:"url"`
	SizeBytes            *int64             `json:"size_bytes"`
	ChecksumSha256       *string            `json:"checksum_sha256"`
	Signature            *string            `json:"signature"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	Filename             *string            `json:"filename"`
	MimeType             *string            `json:"mime_type"`
	MinimumSystemVersion *string            `json:"minimum_system_version"`
	StorageBackend       *string            `json:"storage_backend"`
	StorageKey           *string            `json:"storage_key"`
}

type UpdateChannel struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	ProductID        uuid.UUID          `json:"product_id"`
	Name             string             `json:"name"`
	IsDefault        bool               `json:"is_default"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	RequiredFeatures []string           `json:"required_features"`
	Description      *string            `json:"description"`
}

type UpdateChannelRequiredFeature struct {
	ChannelID uuid.UUID `json:"channel_id"`
	FeatureID uuid.UUID `json:"feature_id"`
}

type UpdateCheck struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    pgtype.UUID        `json:"organization_id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	LicenseID         pgtype.UUID        `json:"license_id"`
	Platform          string             `json:"platform"`
	Channel           string             `json:"channel"`
	ProviderKey       string             `json:"provider_key"`
	CurrentVersion    *string            `json:"current_version"`
	CurrentBuild      *string            `json:"current_build"`
	Arch              *string            `json:"arch"`
	OsVersion         *string            `json:"os_version"`
	Decision          string             `json:"decision"`
	SelectedReleaseID pgtype.UUID        `json:"selected_release_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type UpdateDeltaJob struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	ReleaseID        uuid.UUID          `json:"release_id"`
	SourceReleaseID  uuid.UUID          `json:"source_release_id"`
	SourceArtifactID uuid.UUID          `json:"source_artifact_id"`
	TargetArtifactID uuid.UUID          `json:"target_artifact_id"`
	DeltaArtifactID  pgtype.UUID        `json:"delta_artifact_id"`
	Status           string             `json:"status"`
	SchemaVersion    string             `json:"schema_version"`
	Algorithm        string             `json:"algorithm"`
	SourceSha256     string             `json:"source_sha256"`
	TargetSha256     string             `json:"target_sha256"`
	PatchSha256      *string            `json:"patch_sha256"`
	SourceSize       int64              `json:"source_size"`
	TargetSize       int64              `json:"target_size"`
	PatchSize        *int64             `json:"patch_size"`
	ErrorMessage     *string            `json:"error_message"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
}

type UpdateRelease struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	ChannelID      uuid.UUID          `json:"channel_id"`
	Platform       string             `json:"platform"`
	Version        string             `json:"version"`
	BuildNumber    *string            `json:"build_number"`
	Status         string             `json:"status"`
	ReleaseNotes   *string            `json:"release_notes"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Changelog      *string            `json:"changelog"`
	ChangelogID    pgtype.UUID        `json:"changelog_id"`
}

type UpdateReleasePolicy struct {
	ID                  uuid.UUID          `json:"id"`
	ReleaseID           uuid.UUID          `json:"release_id"`
	Mandatory           bool               `json:"mandatory"`
	MinSupportedVersion *string            `json:"min_supported_version"`
	RolloutPercentage   int32              `json:"rollout_percentage"`
	StartsAt            pgtype.Timestamptz `json:"starts_at"`
	EndsAt              pgtype.Timestamptz `json:"ends_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}
