// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvite = `-- name: AcceptInvite :one
UPDATE organization_invites
SET accepted_at = now()
WHERE id = $1 AND accepted_at IS NULL
RETURNING id, organization_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at
`

func (q *Queries) AcceptInvite(ctx context.Context, id uuid.UUID) (OrganizationInvite, error) {
	row := q.db.QueryRow(ctx, acceptInvite, id)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO organization_invites (organization_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at
`

type CreateInviteParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	Email          string             `json:"email"`
	Role           string             `json:"role"`
	TokenHash      string             `json:"token_hash"`
	InvitedBy      pgtype.UUID        `json:"invited_by"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (OrganizationInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.OrganizationID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM organization_invites
WHERE id = $1 AND organization_id = $2
`

type DeleteInviteParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) error {
	_, err := q.db.Exec(ctx, deleteInvite, arg.ID, arg.OrganizationID)
	return err
}

const deleteOrganizationMember = `-- name: DeleteOrganizationMember :exec
DELETE FROM organization_members
WHERE organization_id = $1 AND admin_user_id = $2
`

type DeleteOrganizationMemberParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	AdminUserID    uuid.UUID `json:"admin_user_id"`
}

func (q *Queries) DeleteOrganizationMember(ctx context.Context, arg DeleteOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, deleteOrganizationMember, arg.OrganizationID, arg.AdminUserID)
	return err
}

const deletePendingInvitesByEmail = `-- name: DeletePendingInvitesByEmail :exec
DELETE FROM organization_invites
WHERE organization_id = $1 AND lower(email) = lower($2) AND accepted_at IS NULL
`

type DeletePendingInvitesByEmailParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Lower          string    `json:"lower"`
}

func (q *Queries) DeletePendingInvitesByEmail(ctx context.Context, arg DeletePendingInvitesByEmailParams) error {
	_, err := q.db.Exec(ctx, deletePendingInvitesByEmail, arg.OrganizationID, arg.Lower)
	return err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT
    i.id,
    i.organization_id,
    i.email,
    i.role,
    i.invited_by,
    i.expires_at,
    i.accepted_at,
    i.created_at,
    o.name AS organization_name,
    o.slug AS organization_slug
FROM organization_invites i
JOIN organizations o ON i.organization_id = o.id
WHERE i.token_hash = $1
`

type GetInviteByTokenHashRow struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	Email            string             `json:"email"`
	Role             string             `json:"role"`
	InvitedBy        pgtype.UUID        `json:"invited_by"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt       pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	OrganizationName string             `json:"organization_name"`
	OrganizationSlug string             `json:"organization_slug"`
}

func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash string) (GetInviteByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i GetInviteByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.OrganizationName,
		&i.OrganizationSlug,
	)
	return i, err
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT au.id, au.email, om.role, om.created_at, au.last_login_at
FROM organization_members om
JOIN admin_users au ON om.admin_user_id = au.id
WHERE om.organization_id = $1
ORDER BY om.created_at
`

type ListOrganizationMembersRow struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembersRow{}
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvites = `-- name: ListPendingInvites :many
SELECT id, email, role, invited_by, expires_at, created_at
FROM organization_invites
WHERE organization_id = $1 AND accepted_at IS NULL
ORDER BY created_at DESC
`

type ListPendingInvitesRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPendingInvites(ctx context.Context, organizationID uuid.UUID) ([]ListPendingInvitesRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvites, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitesRow{}
	for rows.Next() {
		var i ListPendingInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
