// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetActivationsForLicense(ctx context.Context, licenseID pgtype.Int4) ([]Activation, error)
	GetLicenseById(ctx context.Context, id int32) (License, error)
	GetOneById(ctx context.Context, id int32) (Product, error)
	GetProducts(ctx context.Context) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
