// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	ActivateLicense(ctx context.Context, arg ActivateLicenseParams) (Activation, error)
	ConsumeSelfServiceToken(ctx context.Context, tokenHash string) (string, error)
	CountActivations(ctx context.Context, licenseID int32) (int64, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateLicense(ctx context.Context, arg CreateLicenseParams) (License, error)
	CreateSelfServiceLink(ctx context.Context, arg CreateSelfServiceLinkParams) (SelfServiceToken, error)
	GetActivationsForLicense(ctx context.Context, licenseID int32) ([]Activation, error)
	GetLicenseByDigest(ctx context.Context, lookupDigest []byte) (License, error)
	GetLicenseById(ctx context.Context, id int32) (License, error)
	GetOneById(ctx context.Context, id int32) (Product, error)
	GetProducts(ctx context.Context) ([]Product, error)
	ListByCustomerEmail(ctx context.Context, customerEmail string) ([]ListByCustomerEmailRow, error)
}

var _ Querier = (*Queries)(nil)
