// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetLicenseById(ctx context.Context, id int32) (License, error)
}

var _ Querier = (*Queries)(nil)
