// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: selfservice.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeSelfServiceToken = `-- name: ConsumeSelfServiceToken :one
update self_service_tokens
set used_at = now()
where token_hash = $1
    and expires_at > now()
    and used_at is null
returning email
`

func (q *Queries) ConsumeSelfServiceToken(ctx context.Context, tokenHash string) (string, error) {
	row := q.db.QueryRow(ctx, consumeSelfServiceToken, tokenHash)
	var email string
	err := row.Scan(&email)
	return email, err
}

const createSelfServiceLink = `-- name: CreateSelfServiceLink :one
insert into self_service_tokens (
    id,
    email,
    token_hash,
    purpose,
    expires_at,
    created_ip,
    user_agent
)
values (
    gen_random_uuid(),
    $1,
    $2,
    coalesce($3, 'selfservice_login'),
    $4,
    $5,
    $6
)
returning
    id,
    email,
    token_hash,
    purpose,
    expires_at,
    used_at,
    created_at,
    created_ip,
    user_agent
`

type CreateSelfServiceLinkParams struct {
	Email     string             `json:"email"`
	TokenHash string             `json:"token_hash"`
	Purpose   interface{}        `json:"purpose"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedIp *netip.Addr        `json:"created_ip"`
	UserAgent pgtype.Text        `json:"user_agent"`
}

func (q *Queries) CreateSelfServiceLink(ctx context.Context, arg CreateSelfServiceLinkParams) (SelfServiceToken, error) {
	row := q.db.QueryRow(ctx, createSelfServiceLink,
		arg.Email,
		arg.TokenHash,
		arg.Purpose,
		arg.ExpiresAt,
		arg.CreatedIp,
		arg.UserAgent,
	)
	var i SelfServiceToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.CreatedIp,
		&i.UserAgent,
	)
	return i, err
}
