// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getProductStorageConfig = `-- name: GetProductStorageConfig :one
SELECT id, organization_id, product_id, backend, config, created_at, updated_at FROM product_storage_configs
WHERE product_id = $1
`

func (q *Queries) GetProductStorageConfig(ctx context.Context, productID uuid.UUID) (ProductStorageConfig, error) {
	row := q.db.QueryRow(ctx, getProductStorageConfig, productID)
	var i ProductStorageConfig
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Backend,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProductStorageConfig = `-- name: UpsertProductStorageConfig :one
INSERT INTO product_storage_configs (organization_id, product_id, backend, config)
VALUES ($1, $2, $3, $4)
ON CONFLICT (product_id)
DO UPDATE SET
    backend = EXCLUDED.backend,
    config = EXCLUDED.config,
    updated_at = now()
RETURNING id, organization_id, product_id, backend, config, created_at, updated_at
`

type UpsertProductStorageConfigParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProductID      uuid.UUID `json:"product_id"`
	Backend        string    `json:"backend"`
	Config         []byte    `json:"config"`
}

func (q *Queries) UpsertProductStorageConfig(ctx context.Context, arg UpsertProductStorageConfigParams) (ProductStorageConfig, error) {
	row := q.db.QueryRow(ctx, upsertProductStorageConfig,
		arg.OrganizationID,
		arg.ProductID,
		arg.Backend,
		arg.Config,
	)
	var i ProductStorageConfig
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Backend,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
