// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updates.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countConfigsForChannel = `-- name: CountConfigsForChannel :one
SELECT count(*) FROM product_update_configs WHERE channel_id = $1
`

func (q *Queries) CountConfigsForChannel(ctx context.Context, channelID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countConfigsForChannel, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReleasesForChannel = `-- name: CountReleasesForChannel :one
SELECT count(*) FROM update_releases WHERE channel_id = $1
`

func (q *Queries) CountReleasesForChannel(ctx context.Context, channelID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReleasesForChannel, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUpdateChannel = `-- name: CreateUpdateChannel :one
INSERT INTO update_channels (organization_id, product_id, name, is_default, required_features, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, product_id, name, is_default, created_at, updated_at, required_features, description
`

type CreateUpdateChannelParams struct {
	OrganizationID   uuid.UUID `json:"organization_id"`
	ProductID        uuid.UUID `json:"product_id"`
	Name             string    `json:"name"`
	IsDefault        bool      `json:"is_default"`
	RequiredFeatures []string  `json:"required_features"`
	Description      *string   `json:"description"`
}

func (q *Queries) CreateUpdateChannel(ctx context.Context, arg CreateUpdateChannelParams) (UpdateChannel, error) {
	row := q.db.QueryRow(ctx, createUpdateChannel,
		arg.OrganizationID,
		arg.ProductID,
		arg.Name,
		arg.IsDefault,
		arg.RequiredFeatures,
		arg.Description,
	)
	var i UpdateChannel
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequiredFeatures,
		&i.Description,
	)
	return i, err
}

const deleteExpiredUpdateChecks = `-- name: DeleteExpiredUpdateChecks :execrows
DELETE FROM update_checks
WHERE created_at < now() - make_interval(days => $1::int)
`

func (q *Queries) DeleteExpiredUpdateChecks(ctx context.Context, retentionDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredUpdateChecks, retentionDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProductUpdateConfig = `-- name: DeleteProductUpdateConfig :one
DELETE FROM product_update_configs
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, product_id, platform, channel_id, provider_key, config, enabled, created_at, updated_at
`

type DeleteProductUpdateConfigParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteProductUpdateConfig(ctx context.Context, arg DeleteProductUpdateConfigParams) (ProductUpdateConfig, error) {
	row := q.db.QueryRow(ctx, deleteProductUpdateConfig, arg.ID, arg.OrganizationID)
	var i ProductUpdateConfig
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Platform,
		&i.ChannelID,
		&i.ProviderKey,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUpdateChannel = `-- name: DeleteUpdateChannel :one
DELETE FROM update_channels
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, product_id, name, is_default, created_at, updated_at, required_features, description
`

type DeleteUpdateChannelParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteUpdateChannel(ctx context.Context, arg DeleteUpdateChannelParams) (UpdateChannel, error) {
	row := q.db.QueryRow(ctx, deleteUpdateChannel, arg.ID, arg.OrganizationID)
	var i UpdateChannel
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequiredFeatures,
		&i.Description,
	)
	return i, err
}

const deleteUpdateRelease = `-- name: DeleteUpdateRelease :one
DELETE FROM update_releases
WHERE id = $1
RETURNING id, organization_id, product_id, channel_id, platform, version, build_number, status, release_notes, published_at, created_at, updated_at, changelog, changelog_id
`

func (q *Queries) DeleteUpdateRelease(ctx context.Context, id uuid.UUID) (UpdateRelease, error) {
	row := q.db.QueryRow(ctx, deleteUpdateRelease, id)
	var i UpdateRelease
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.ChannelID,
		&i.Platform,
		&i.Version,
		&i.BuildNumber,
		&i.Status,
		&i.ReleaseNotes,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Changelog,
		&i.ChangelogID,
	)
	return i, err
}

const getChangelogsByReleaseIDs = `-- name: GetChangelogsByReleaseIDs :many
SELECT r.id AS release_id, c.body AS changelog_body
FROM update_releases r
JOIN changelogs c ON c.id = r.changelog_id
WHERE r.id = ANY($1::uuid[])
`

type GetChangelogsByReleaseIDsRow struct {
	ReleaseID     uuid.UUID `json:"release_id"`
	ChangelogBody string    `json:"changelog_body"`
}

func (q *Queries) GetChangelogsByReleaseIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetChangelogsByReleaseIDsRow, error) {
	rows, err := q.db.Query(ctx, getChangelogsByReleaseIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChangelogsByReleaseIDsRow{}
	for rows.Next() {
		var i GetChangelogsByReleaseIDsRow
		if err := rows.Scan(&i.ReleaseID, &i.ChangelogBody); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelByProductAndName = `-- name: GetChannelByProductAndName :one
SELECT id, organization_id, product_id, name, is_default, created_at, updated_at, required_features, description FROM update_channels
WHERE product_id = $1 AND name = $2
`

type GetChannelByProductAndNameParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Name      string    `json:"name"`
}

func (q *Queries) GetChannelByProductAndName(ctx context.Context, arg GetChannelByProductAndNameParams) (UpdateChannel, error) {
	row := q.db.QueryRow(ctx, getChannelByProductAndName, arg.ProductID, arg.Name)
	var i UpdateChannel
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequiredFeatures,
		&i.Description,
	)
	return i, err
}

const getChannelsForProduct = `-- name: GetChannelsForProduct :many
SELECT id, organization_id, product_id, name, is_default, created_at, updated_at, required_features, description FROM update_channels
WHERE product_id = $1
ORDER BY name
`

func (q *Queries) GetChannelsForProduct(ctx context.Context, productID uuid.UUID) ([]UpdateChannel, error) {
	rows, err := q.db.Query(ctx, getChannelsForProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UpdateChannel{}
	for rows.Next() {
		var i UpdateChannel
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProductID,
			&i.Name,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequiredFeatures,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDefaultChannelForProduct = `-- name: GetDefaultChannelForProduct :one
SELECT id, organization_id, product_id, name, is_default, created_at, updated_at, required_features, description FROM update_channels
WHERE product_id = $1 AND is_default = true
LIMIT 1
`

func (q *Queries) GetDefaultChannelForProduct(ctx context.Context, productID uuid.UUID) (UpdateChannel, error) {
	row := q.db.QueryRow(ctx, getDefaultChannelForProduct, productID)
	var i UpdateChannel
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequiredFeatures,
		&i.Description,
	)
	return i, err
}

const getProductUpdateConfig = `-- name: GetProductUpdateConfig :one
SELECT puc.id, puc.organization_id, puc.product_id, puc.platform, puc.channel_id, puc.provider_key, puc.config, puc.enabled, puc.created_at, puc.updated_at, c.required_features AS channel_required_features
FROM product_update_configs puc
JOIN update_channels c ON c.id = puc.channel_id
WHERE puc.product_id = $1
  AND puc.platform = $2
  AND c.name = $3
  AND puc.enabled = true
`

type GetProductUpdateConfigParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Platform  string    `json:"platform"`
	Name      string    `json:"name"`
}

type GetProductUpdateConfigRow struct {
	ID                      uuid.UUID          `json:"id"`
	OrganizationID          uuid.UUID          `json:"organization_id"`
	ProductID               uuid.UUID          `json:"product_id"`
	Platform                string             `json:"platform"`
	ChannelID               uuid.UUID          `json:"channel_id"`
	ProviderKey             string             `json:"provider_key"`
	Config                  []byte             `json:"config"`
	Enabled                 bool               `json:"enabled"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	ChannelRequiredFeatures []string           `json:"channel_required_features"`
}

func (q *Queries) GetProductUpdateConfig(ctx context.Context, arg GetProductUpdateConfigParams) (GetProductUpdateConfigRow, error) {
	row := q.db.QueryRow(ctx, getProductUpdateConfig, arg.ProductID, arg.Platform, arg.Name)
	var i GetProductUpdateConfigRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Platform,
		&i.ChannelID,
		&i.ProviderKey,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChannelRequiredFeatures,
	)
	return i, err
}

const getProductUpdateConfigs = `-- name: GetProductUpdateConfigs :many
SELECT puc.id, puc.organization_id, puc.product_id, puc.platform, puc.channel_id, puc.provider_key, puc.config, puc.enabled, puc.created_at, puc.updated_at, c.name AS channel_name
FROM product_update_configs puc
JOIN update_channels c ON c.id = puc.channel_id
WHERE puc.product_id = $1
ORDER BY puc.platform, c.name
`

type GetProductUpdateConfigsRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	Platform       string             `json:"platform"`
	ChannelID      uuid.UUID          `json:"channel_id"`
	ProviderKey    string             `json:"provider_key"`
	Config         []byte             `json:"config"`
	Enabled        bool               `json:"enabled"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ChannelName    string             `json:"channel_name"`
}

func (q *Queries) GetProductUpdateConfigs(ctx context.Context, productID uuid.UUID) ([]GetProductUpdateConfigsRow, error) {
	rows, err := q.db.Query(ctx, getProductUpdateConfigs, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductUpdateConfigsRow{}
	for rows.Next() {
		var i GetProductUpdateConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProductID,
			&i.Platform,
			&i.ChannelID,
			&i.ProviderKey,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReleasePoliciesForReleases = `-- name: GetReleasePoliciesForReleases :many
SELECT id, release_id, mandatory, min_supported_version, rollout_percentage, starts_at, ends_at, created_at, updated_at FROM update_release_policies
WHERE release_id = ANY($1::uuid[])
`

func (q *Queries) GetReleasePoliciesForReleases(ctx context.Context, dollar_1 []uuid.UUID) ([]UpdateReleasePolicy, error) {
	rows, err := q.db.Query(ctx, getReleasePoliciesForReleases, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UpdateReleasePolicy{}
	for rows.Next() {
		var i UpdateReleasePolicy
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.Mandatory,
			&i.MinSupportedVersion,
			&i.RolloutPercentage,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReleasePolicy = `-- name: GetReleasePolicy :one
SELECT id, release_id, mandatory, min_supported_version, rollout_percentage, starts_at, ends_at, created_at, updated_at FROM update_release_policies
WHERE release_id = $1
`

func (q *Queries) GetReleasePolicy(ctx context.Context, releaseID uuid.UUID) (UpdateReleasePolicy, error) {
	row := q.db.QueryRow(ctx, getReleasePolicy, releaseID)
	var i UpdateReleasePolicy
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Mandatory,
		&i.MinSupportedVersion,
		&i.RolloutPercentage,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUpdateArtifact = `-- name: GetUpdateArtifact :one
SELECT id, release_id, artifact_type, os, arch, url, size_bytes, checksum_sha256, signature, metadata, created_at, filename, mime_type, minimum_system_version, storage_backend, storage_key FROM update_artifacts WHERE id = $1
`

func (q *Queries) GetUpdateArtifact(ctx context.Context, id uuid.UUID) (UpdateArtifact, error) {
	row := q.db.QueryRow(ctx, getUpdateArtifact, id)
	var i UpdateArtifact
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ArtifactType,
		&i.Os,
		&i.Arch,
		&i.Url,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.Signature,
		&i.Metadata,
		&i.CreatedAt,
		&i.Filename,
		&i.MimeType,
		&i.MinimumSystemVersion,
		&i.StorageBackend,
		&i.StorageKey,
	)
	return i, err
}

const getUpdateChannelByID = `-- name: GetUpdateChannelByID :one
SELECT id, organization_id, product_id, name, is_default, created_at, updated_at, required_features, description FROM update_channels WHERE id = $1
`

func (q *Queries) GetUpdateChannelByID(ctx context.Context, id uuid.UUID) (UpdateChannel, error) {
	row := q.db.QueryRow(ctx, getUpdateChannelByID, id)
	var i UpdateChannel
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequiredFeatures,
		&i.Description,
	)
	return i, err
}

const getUpdateRelease = `-- name: GetUpdateRelease :one
SELECT id, organization_id, product_id, channel_id, platform, version, build_number, status, release_notes, published_at, created_at, updated_at, changelog, changelog_id FROM update_releases WHERE id = $1
`

func (q *Queries) GetUpdateRelease(ctx context.Context, id uuid.UUID) (UpdateRelease, error) {
	row := q.db.QueryRow(ctx, getUpdateRelease, id)
	var i UpdateRelease
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.ChannelID,
		&i.Platform,
		&i.Version,
		&i.BuildNumber,
		&i.Status,
		&i.ReleaseNotes,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Changelog,
		&i.ChangelogID,
	)
	return i, err
}

const insertUpdateArtifact = `-- name: InsertUpdateArtifact :one
INSERT INTO update_artifacts (
    id, release_id, artifact_type, os, arch, url, size_bytes, checksum_sha256, signature, metadata,
    filename, mime_type, minimum_system_version, storage_backend, storage_key
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, release_id, artifact_type, os, arch, url, size_bytes, checksum_sha256, signature, metadata, created_at, filename, mime_type, minimum_system_version, storage_backend, storage_key
`

type InsertUpdateArtifactParams struct {
	ID                   uuid.UUID `json:"id"`
	ReleaseID            uuid.UUID `json:"release_id"`
	ArtifactType         string    `json:"artifact_type"`
	Os                   string    `json:"os"`
	Arch                 string    `json:"arch"`
	Url                  string    `json:"url"`
	SizeBytes            *int64    `json:"size_bytes"`
	ChecksumSha256       *string   `json:"checksum_sha256"`
	Signature            *string   `json:"signature"`
	Metadata             []byte    `json:"metadata"`
	Filename             *string   `json:"filename"`
	MimeType             *string   `json:"mime_type"`
	MinimumSystemVersion *string   `json:"minimum_system_version"`
	StorageBackend       *string   `json:"storage_backend"`
	StorageKey           *string   `json:"storage_key"`
}

func (q *Queries) InsertUpdateArtifact(ctx context.Context, arg InsertUpdateArtifactParams) (UpdateArtifact, error) {
	row := q.db.QueryRow(ctx, insertUpdateArtifact,
		arg.ID,
		arg.ReleaseID,
		arg.ArtifactType,
		arg.Os,
		arg.Arch,
		arg.Url,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.Signature,
		arg.Metadata,
		arg.Filename,
		arg.MimeType,
		arg.MinimumSystemVersion,
		arg.StorageBackend,
		arg.StorageKey,
	)
	var i UpdateArtifact
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ArtifactType,
		&i.Os,
		&i.Arch,
		&i.Url,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.Signature,
		&i.Metadata,
		&i.CreatedAt,
		&i.Filename,
		&i.MimeType,
		&i.MinimumSystemVersion,
		&i.StorageBackend,
		&i.StorageKey,
	)
	return i, err
}

const insertUpdateCheck = `-- name: InsertUpdateCheck :one
INSERT INTO update_checks (
    organization_id, product_id, license_id, platform, channel,
    provider_key, current_version, current_build, arch, os_version, decision, selected_release_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, organization_id, product_id, license_id, platform, channel, provider_key, current_version, current_build, arch, os_version, decision, selected_release_id, created_at
`

type InsertUpdateCheckParams struct {
	OrganizationID    pgtype.UUID `json:"organization_id"`
	ProductID         pgtype.UUID `json:"product_id"`
	LicenseID         pgtype.UUID `json:"license_id"`
	Platform          string      `json:"platform"`
	Channel           string      `json:"channel"`
	ProviderKey       string      `json:"provider_key"`
	CurrentVersion    *string     `json:"current_version"`
	CurrentBuild      *string     `json:"current_build"`
	Arch              *string     `json:"arch"`
	OsVersion         *string     `json:"os_version"`
	Decision          string      `json:"decision"`
	SelectedReleaseID pgtype.UUID `json:"selected_release_id"`
}

func (q *Queries) InsertUpdateCheck(ctx context.Context, arg InsertUpdateCheckParams) (UpdateCheck, error) {
	row := q.db.QueryRow(ctx, insertUpdateCheck,
		arg.OrganizationID,
		arg.ProductID,
		arg.LicenseID,
		arg.Platform,
		arg.Channel,
		arg.ProviderKey,
		arg.CurrentVersion,
		arg.CurrentBuild,
		arg.Arch,
		arg.OsVersion,
		arg.Decision,
		arg.SelectedReleaseID,
	)
	var i UpdateCheck
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.LicenseID,
		&i.Platform,
		&i.Channel,
		&i.ProviderKey,
		&i.CurrentVersion,
		&i.CurrentBuild,
		&i.Arch,
		&i.OsVersion,
		&i.Decision,
		&i.SelectedReleaseID,
		&i.CreatedAt,
	)
	return i, err
}

const insertUpdateRelease = `-- name: InsertUpdateRelease :one
INSERT INTO update_releases (
    organization_id, product_id, channel_id, platform,
    version, build_number, status, release_notes, published_at, changelog_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, organization_id, product_id, channel_id, platform, version, build_number, status, release_notes, published_at, created_at, updated_at, changelog, changelog_id
`

type InsertUpdateReleaseParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	ChannelID      uuid.UUID          `json:"channel_id"`
	Platform       string             `json:"platform"`
	Version        string             `json:"version"`
	BuildNumber    *string            `json:"build_number"`
	Status         string             `json:"status"`
	ReleaseNotes   *string            `json:"release_notes"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	ChangelogID    pgtype.UUID        `json:"changelog_id"`
}

func (q *Queries) InsertUpdateRelease(ctx context.Context, arg InsertUpdateReleaseParams) (UpdateRelease, error) {
	row := q.db.QueryRow(ctx, insertUpdateRelease,
		arg.OrganizationID,
		arg.ProductID,
		arg.ChannelID,
		arg.Platform,
		arg.Version,
		arg.BuildNumber,
		arg.Status,
		arg.ReleaseNotes,
		arg.PublishedAt,
		arg.ChangelogID,
	)
	var i UpdateRelease
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.ChannelID,
		&i.Platform,
		&i.Version,
		&i.BuildNumber,
		&i.Status,
		&i.ReleaseNotes,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Changelog,
		&i.ChangelogID,
	)
	return i, err
}

const latestPublishedUpdateRelease = `-- name: LatestPublishedUpdateRelease :one
SELECT id, organization_id, product_id, channel_id, platform, version, build_number, status, release_notes, published_at, created_at, updated_at, changelog, changelog_id
FROM update_releases
WHERE product_id = $1
  AND platform = $2
  AND channel_id = $3
  AND status = 'published'
  AND published_at <= now()
ORDER BY published_at DESC, created_at DESC
LIMIT 1
`

type LatestPublishedUpdateReleaseParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Platform  string    `json:"platform"`
	ChannelID uuid.UUID `json:"channel_id"`
}

func (q *Queries) LatestPublishedUpdateRelease(ctx context.Context, arg LatestPublishedUpdateReleaseParams) (UpdateRelease, error) {
	row := q.db.QueryRow(ctx, latestPublishedUpdateRelease, arg.ProductID, arg.Platform, arg.ChannelID)
	var i UpdateRelease
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.ChannelID,
		&i.Platform,
		&i.Version,
		&i.BuildNumber,
		&i.Status,
		&i.ReleaseNotes,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Changelog,
		&i.ChangelogID,
	)
	return i, err
}

const listArtifactsForRelease = `-- name: ListArtifactsForRelease :many
SELECT id, release_id, artifact_type, os, arch, url, size_bytes, checksum_sha256, signature, metadata, created_at, filename, mime_type, minimum_system_version, storage_backend, storage_key FROM update_artifacts
WHERE release_id = $1
`

func (q *Queries) ListArtifactsForRelease(ctx context.Context, releaseID uuid.UUID) ([]UpdateArtifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsForRelease, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UpdateArtifact{}
	for rows.Next() {
		var i UpdateArtifact
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.ArtifactType,
			&i.Os,
			&i.Arch,
			&i.Url,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.Signature,
			&i.Metadata,
			&i.CreatedAt,
			&i.Filename,
			&i.MimeType,
			&i.MinimumSystemVersion,
			&i.StorageBackend,
			&i.StorageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsForReleases = `-- name: ListArtifactsForReleases :many
SELECT id, release_id, artifact_type, os, arch, url, size_bytes, checksum_sha256, signature, metadata, created_at, filename, mime_type, minimum_system_version, storage_backend, storage_key FROM update_artifacts
WHERE release_id = ANY($1::uuid[])
`

func (q *Queries) ListArtifactsForReleases(ctx context.Context, dollar_1 []uuid.UUID) ([]UpdateArtifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsForReleases, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UpdateArtifact{}
	for rows.Next() {
		var i UpdateArtifact
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.ArtifactType,
			&i.Os,
			&i.Arch,
			&i.Url,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.Signature,
			&i.Metadata,
			&i.CreatedAt,
			&i.Filename,
			&i.MimeType,
			&i.MinimumSystemVersion,
			&i.StorageBackend,
			&i.StorageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedReleasesForFeed = `-- name: ListPublishedReleasesForFeed :many
SELECT id, organization_id, product_id, channel_id, platform, version, build_number, status, release_notes, published_at, created_at, updated_at, changelog, changelog_id
FROM update_releases
WHERE product_id = $1
  AND platform = $2
  AND channel_id = $3
  AND status = 'published'
  AND published_at <= now()
ORDER BY published_at DESC
LIMIT 20
`

type ListPublishedReleasesForFeedParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Platform  string    `json:"platform"`
	ChannelID uuid.UUID `json:"channel_id"`
}

func (q *Queries) ListPublishedReleasesForFeed(ctx context.Context, arg ListPublishedReleasesForFeedParams) ([]UpdateRelease, error) {
	rows, err := q.db.Query(ctx, listPublishedReleasesForFeed, arg.ProductID, arg.Platform, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UpdateRelease{}
	for rows.Next() {
		var i UpdateRelease
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProductID,
			&i.ChannelID,
			&i.Platform,
			&i.Version,
			&i.BuildNumber,
			&i.Status,
			&i.ReleaseNotes,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Changelog,
			&i.ChangelogID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasesForOrganization = `-- name: ListReleasesForOrganization :many
SELECT ur.id, ur.organization_id, ur.product_id, ur.channel_id, ur.platform, ur.version, ur.build_number, ur.status, ur.release_notes, ur.published_at, ur.created_at, ur.updated_at, ur.changelog, ur.changelog_id, p.name AS product_name, c.name AS channel_name
FROM update_releases ur
JOIN products p ON p.id = ur.product_id
JOIN update_channels c ON c.id = ur.channel_id
WHERE ur.organization_id = $1
ORDER BY ur.created_at DESC
LIMIT $2 OFFSET $3
`

type ListReleasesForOrganizationParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

type ListReleasesForOrganizationRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	ChannelID      uuid.UUID          `json:"channel_id"`
	Platform       string             `json:"platform"`
	Version        string             `json:"version"`
	BuildNumber    *string            `json:"build_number"`
	Status         string             `json:"status"`
	ReleaseNotes   *string            `json:"release_notes"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Changelog      *string            `json:"changelog"`
	ChangelogID    pgtype.UUID        `json:"changelog_id"`
	ProductName    string             `json:"product_name"`
	ChannelName    string             `json:"channel_name"`
}

func (q *Queries) ListReleasesForOrganization(ctx context.Context, arg ListReleasesForOrganizationParams) ([]ListReleasesForOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listReleasesForOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleasesForOrganizationRow{}
	for rows.Next() {
		var i ListReleasesForOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProductID,
			&i.ChannelID,
			&i.Platform,
			&i.Version,
			&i.BuildNumber,
			&i.Status,
			&i.ReleaseNotes,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Changelog,
			&i.ChangelogID,
			&i.ProductName,
			&i.ChannelName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasesForOrganizationByProduct = `-- name: ListReleasesForOrganizationByProduct :many
SELECT ur.id, ur.organization_id, ur.product_id, ur.channel_id, ur.platform, ur.version, ur.build_number, ur.status, ur.release_notes, ur.published_at, ur.created_at, ur.updated_at, ur.changelog, ur.changelog_id, p.name AS product_name, c.name AS channel_name
FROM update_releases ur
JOIN products p ON p.id = ur.product_id
JOIN update_channels c ON c.id = ur.channel_id
WHERE ur.organization_id = $1 AND ur.product_id = $2
ORDER BY ur.created_at DESC
LIMIT $3 OFFSET $4
`

type ListReleasesForOrganizationByProductParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProductID      uuid.UUID `json:"product_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

type ListReleasesForOrganizationByProductRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	ChannelID      uuid.UUID          `json:"channel_id"`
	Platform       string             `json:"platform"`
	Version        string             `json:"version"`
	BuildNumber    *string            `json:"build_number"`
	Status         string             `json:"status"`
	ReleaseNotes   *string            `json:"release_notes"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Changelog      *string            `json:"changelog"`
	ChangelogID    pgtype.UUID        `json:"changelog_id"`
	ProductName    string             `json:"product_name"`
	ChannelName    string             `json:"channel_name"`
}

func (q *Queries) ListReleasesForOrganizationByProduct(ctx context.Context, arg ListReleasesForOrganizationByProductParams) ([]ListReleasesForOrganizationByProductRow, error) {
	rows, err := q.db.Query(ctx, listReleasesForOrganizationByProduct,
		arg.OrganizationID,
		arg.ProductID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleasesForOrganizationByProductRow{}
	for rows.Next() {
		var i ListReleasesForOrganizationByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProductID,
			&i.ChannelID,
			&i.Platform,
			&i.Version,
			&i.BuildNumber,
			&i.Status,
			&i.ReleaseNotes,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Changelog,
			&i.ChangelogID,
			&i.ProductName,
			&i.ChannelName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishUpdateRelease = `-- name: PublishUpdateRelease :one
UPDATE update_releases
SET status = 'published', published_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, organization_id, product_id, channel_id, platform, version, build_number, status, release_notes, published_at, created_at, updated_at, changelog, changelog_id
`

func (q *Queries) PublishUpdateRelease(ctx context.Context, id uuid.UUID) (UpdateRelease, error) {
	row := q.db.QueryRow(ctx, publishUpdateRelease, id)
	var i UpdateRelease
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.ChannelID,
		&i.Platform,
		&i.Version,
		&i.BuildNumber,
		&i.Status,
		&i.ReleaseNotes,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Changelog,
		&i.ChangelogID,
	)
	return i, err
}

const updateUpdateChannel = `-- name: UpdateUpdateChannel :one
UPDATE update_channels
SET name = $3,
    is_default = $4,
    required_features = $5,
    description = $6,
    updated_at = now()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, product_id, name, is_default, created_at, updated_at, required_features, description
`

type UpdateUpdateChannelParams struct {
	ID               uuid.UUID `json:"id"`
	OrganizationID   uuid.UUID `json:"organization_id"`
	Name             string    `json:"name"`
	IsDefault        bool      `json:"is_default"`
	RequiredFeatures []string  `json:"required_features"`
	Description      *string   `json:"description"`
}

func (q *Queries) UpdateUpdateChannel(ctx context.Context, arg UpdateUpdateChannelParams) (UpdateChannel, error) {
	row := q.db.QueryRow(ctx, updateUpdateChannel,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.IsDefault,
		arg.RequiredFeatures,
		arg.Description,
	)
	var i UpdateChannel
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequiredFeatures,
		&i.Description,
	)
	return i, err
}

const upsertProductUpdateConfig = `-- name: UpsertProductUpdateConfig :one
INSERT INTO product_update_configs (
    organization_id, product_id, platform, channel_id, provider_key, config, enabled
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (product_id, platform, channel_id)
DO UPDATE SET
    provider_key = EXCLUDED.provider_key,
    config = EXCLUDED.config,
    enabled = EXCLUDED.enabled,
    updated_at = now()
RETURNING id, organization_id, product_id, platform, channel_id, provider_key, config, enabled, created_at, updated_at
`

type UpsertProductUpdateConfigParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProductID      uuid.UUID `json:"product_id"`
	Platform       string    `json:"platform"`
	ChannelID      uuid.UUID `json:"channel_id"`
	ProviderKey    string    `json:"provider_key"`
	Config         []byte    `json:"config"`
	Enabled        bool      `json:"enabled"`
}

func (q *Queries) UpsertProductUpdateConfig(ctx context.Context, arg UpsertProductUpdateConfigParams) (ProductUpdateConfig, error) {
	row := q.db.QueryRow(ctx, upsertProductUpdateConfig,
		arg.OrganizationID,
		arg.ProductID,
		arg.Platform,
		arg.ChannelID,
		arg.ProviderKey,
		arg.Config,
		arg.Enabled,
	)
	var i ProductUpdateConfig
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Platform,
		&i.ChannelID,
		&i.ProviderKey,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUpdateChannel = `-- name: UpsertUpdateChannel :one
INSERT INTO update_channels (organization_id, product_id, name, is_default)
VALUES ($1, $2, $3, $4)
ON CONFLICT (product_id, name)
DO UPDATE SET is_default = EXCLUDED.is_default, updated_at = now()
RETURNING id, organization_id, product_id, name, is_default, created_at, updated_at, required_features, description
`

type UpsertUpdateChannelParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProductID      uuid.UUID `json:"product_id"`
	Name           string    `json:"name"`
	IsDefault      bool      `json:"is_default"`
}

func (q *Queries) UpsertUpdateChannel(ctx context.Context, arg UpsertUpdateChannelParams) (UpdateChannel, error) {
	row := q.db.QueryRow(ctx, upsertUpdateChannel,
		arg.OrganizationID,
		arg.ProductID,
		arg.Name,
		arg.IsDefault,
	)
	var i UpdateChannel
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequiredFeatures,
		&i.Description,
	)
	return i, err
}

const yankUpdateRelease = `-- name: YankUpdateRelease :one
UPDATE update_releases
SET status = 'yanked', updated_at = now()
WHERE id = $1
RETURNING id, organization_id, product_id, channel_id, platform, version, build_number, status, release_notes, published_at, created_at, updated_at, changelog, changelog_id
`

func (q *Queries) YankUpdateRelease(ctx context.Context, id uuid.UUID) (UpdateRelease, error) {
	row := q.db.QueryRow(ctx, yankUpdateRelease, id)
	var i UpdateRelease
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProductID,
		&i.ChannelID,
		&i.Platform,
		&i.Version,
		&i.BuildNumber,
		&i.Status,
		&i.ReleaseNotes,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Changelog,
		&i.ChangelogID,
	)
	return i, err
}
